### ISSUE TITLE
75.0.3770.15 can not log in

### ISSUE THREAD

**Issue by appleshowc** [jjqqkk/chromium#100]
Version: **Windows 75.0.3770.15**

When chromium first opens, it displays **sync error**.
Then I log out and try to log in again.
[**Login page**](https://accounts.google.com/signin/chrome/sync?ssp=1&continue=https%3A%2F%2Fwww.google.com%2F) displays **ERROR 404**.

I **CANNOT** log in anymore!!! So sad...

**Comment by jjqqkk** [comment]
Google sync is not configured in Chromium, you cannot login the browser. However you are still be able to login any website as you would in stable Chrome.

**Comment by appleshowc** [comment]
@jjqqkk Thanks for your reply!
But, how should I sync browser settings?
