### ISSUE TITLE
Windows Installer 程序包 JJQQKK -1.0.0.msi 双击后没有任何反应 无法正常打开

### ISSUE THREAD

**Issue by Shadowannarock** [jjqqkk/chromium#101]

**Comment by Shadowannarock** [comment]
![JJQQKK-1 0 0](https://user-images.githubusercontent.com/39541622/57355755-54546080-71a1-11e9-9676-17cee314c204.png)

**Comment by jjqqkk** [comment]
是.msi 安装包不是.exe

**Comment by Shadowannarock** [comment]
@jjqqkk  
这是点击安装包之后的桌面快捷方式图标
![JJQQKK](https://user-images.githubusercontent.com/39541622/57358450-098a1700-71a8-11e9-8d15-0d5a10b22a54.png)
BUG！！！
![Microsoft NET Framework](https://user-images.githubusercontent.com/39541622/57358503-29213f80-71a8-11e9-8cd6-98c607e38f18.png)

**Comment by Shadowannarock** [comment]
@jjqqkk 
这是详细信息

**Comment by jjqqkk** [comment]
windows和.net版本？
