### ISSUE TITLE
你好，我的Macpro，安装pkg之后，点击启动chromiun按钮没有反应，是什么原因？

### ISSUE THREAD

**Issue by Damsir** [jjqqkk/chromium#102]

**Comment by jjqqkk** [comment]
mac版本？

**Comment by Damsir** [comment]
嗯嗯，对

**Comment by jjqqkk** [comment]
会不会用Mac命令行，可以试试以下命令：
```
/Applications/JJQQKK.app/Contents/Resources/helper update
```

正常输出结果：
```
2019/05/11 20:47:06 [/Applications/JJQQKK.app/Contents/Resources/helper update]
update: 0
```

你如果看到不同结果，贴上来

**Comment by Damsir** [comment]
结果是一样的，那是不是每次都需要执行这个命令来检查更新呀？

**Comment by jjqqkk** [comment]
不需要 现在浏览器还是打不开？

**Comment by Damsir** [comment]
<img width="371" alt="image" src="https://user-images.githubusercontent.com/16216553/57592833-46208e80-756b-11e9-9416-eb9b56e9642b.png">
点击之后没有任何反应，这个状态栏（JJQQKK）就消失了

**Comment by jjqqkk** [comment]
看起来是app崩溃了，但具体原因我们也不知道，目前只有您一人报告这个问题。尽快更新版本，看看能不能找到原因。

不如再试试这个命令：
/Applications/JJQQKK.app/Contents/Resources/helper update

有没有反应？

**Comment by Damsir** [comment]
<img width="431" alt="image" src="https://user-images.githubusercontent.com/16216553/57610799-0924be00-75a4-11e9-89f9-72b8b7dde559.png">
更新了，但是还是和原来一样，没有反应。对了，这个安装方法，没有太看懂，我是直接按照正常的方式安装的，会有问题吗？
<img width="717" alt="image" src="https://user-images.githubusercontent.com/16216553/57610948-5e60cf80-75a4-11e9-9eb7-c68433be9831.png">

**Comment by jjqqkk** [comment]
看起来完全没问题，命令行应该能打开浏览器，试试看：

```
/Applications/JJQQKK.app/Contents/Resources/helper open-chromium
```

启动栏图标消失的确没遇到过，需要再研究研究。

按住Command是因为安装包没有签名，正常双击打开的时候Mac会提示一堆废话，然后不让你安装，按住Command从弹出菜单里打开就能正常安装。

**Comment by Damsir** [comment]
这个是怎么自动更新版本的？怎么操作的

**Comment by jjqqkk** [comment]
@Damsir 什么都不用做 会自动下载 再次打开浏览器时就是新版

**Comment by jjqqkk** [comment]
@Damsir macOS版本多少 是不是10.12或以下

**Comment by Damsir** [comment]
<img width="588" alt="image" src="https://user-images.githubusercontent.com/16216553/57833379-775bc180-77ec-11e9-8342-a7439dc1a56e.png">

**Comment by jjqqkk** [comment]
oh 终于找到原因 10.12兼容性有点小问题

**Comment by Damsir** [comment]
哦哦，修复这个问题要多久呀？
