### ISSUE TITLE
建议Mac版把chromium下载目录直接设置在Application下

### ISSUE THREAD

**Issue by mars-9527** [jjqqkk/chromium#105]
默认的下载路径无法导入API秘钥，还得自己手动拷贝到Application路径下

**Comment by laoduu** [comment]
现在在Application路径下哪个目录啊，找半天没找到啊

**Comment by TT1890155** [comment]
> 默认的下载路径无法导入API秘钥，还得自己手动拷贝到Application路径下

你好=。=请问MAC怎么导入API秘钥啊，我照着一个
https://blog.csdn.net/sinat_21302587/article/details/84960580
这里操作，第二步的时候总是出错。
