### ISSUE TITLE
Win10 安装jjqqkk安装器后，右下角点图标，打开Chromium没有任何反应

### ISSUE THREAD

**Issue by WilsonPong** [jjqqkk/chromium#106]
Win10 安装jjqqkk安装器后，右下角点图标，打开Chromium没有任何反应

**Comment by jjqqkk** [comment]
Please paste your Windows version: press "windows-R" on the keyboard, then run "winver", it tells you the version like win10, build 1809, blabla..

**Comment by lxk1997** [comment]
win10 build 1803

**Comment by WilsonPong** [comment]
Win10
版本1803 （OS内部版本 17134.706）

**Comment by jinsetudi** [comment]
1903（OS内部版本18362.418）
