### ISSUE TITLE
网速很慢啊

### ISSUE THREAD

**Issue by WCNMDBBBBB** [jjqqkk/chromium#107]
### mac用来翻墙网速很慢啊，只能用最低的画质

**Comment by LiWeiQiangAndroid** [comment]
可以放网盘多好？

**Comment by jjqqkk** [comment]
关掉再开有可能会快点，中国大陆的晚上7-10点连接美国很慢，这是受到整体光缆出口速度限制

**Comment by 43846582** [comment]
> 關掉再開有可能會快點，中國大陸的晚上7-10點連接美國很慢，這是受到整體光纜出口速度限制

哦～～～～难怪了

**Comment by Frankienashi** [comment]
> 关掉再开有可能会快点，中国大陆的晚上7-10点连接美国很慢，这是受到整体光缆出口速度限制

对对对那个时间特点慢。感觉凌晨1点到五点会比较快

**Comment by LiWeiQiangAndroid** [comment]
使用这个工具下很快 https://github.com/proxyee-down-org/proxyee-down
