### ISSUE TITLE
无法联网了

### ISSUE THREAD

**Issue by liao2012** [jjqqkk/chromium#111]
提示“缺少GOOGLE API 密钥，因此Chromium的部分功能降无法使用”。

**Comment by luoshupeng** [comment]
自己谷歌或者百度一下就可以解决了

**Comment by liao2012** [comment]
好的。




------------------ 原始邮件 ------------------
发件人: "luoshupeng"<notifications@github.com>; 
发送时间: 2019年5月29日(星期三) 上午7:37
收件人: "jjqqkk/chromium"<chromium@noreply.github.com>; 
抄送: "李奥"<345740839@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [jjqqkk/chromium] 无法联网了 (#111)




自己谷歌或者百度一下就可以解决了
