### ISSUE TITLE
你好，这个启动全文加速后，好像网速几乎没有，不知道什么原因，你那边会吗？

### ISSUE THREAD

**Issue by Damsir** [jjqqkk/chromium#112]
你好，这个启动全文加速后，好像网速几乎没有，不知道什么原因，你那边会吗？

**Comment by jjqqkk** [comment]
macOS版本？

启动后用命令行检查一下：

```route -n get default | grep gateway```

```networksetup -getdnsservers wi-fi```

**Comment by Damsir** [comment]
<img width="525" alt="image" src="https://user-images.githubusercontent.com/16216553/58526978-73279f00-8203-11e9-88f5-e03a793febbc.png">
macOS 10.12.6 ,上面的是没开启全网加速的，下面是开启后的

**Comment by LiWeiQiangAndroid** [comment]
开全网加速走代理反而慢了，墙外可能好点

**Comment by jjqqkk** [comment]
@all 用了vpn就不必再通过chromium上网，可以直接用其他浏览器，vpn和chromium是二选一的解决方案
