### ISSUE TITLE
好像不都不能使用了，

### ISSUE THREAD

**Issue by summersir** [jjqqkk/chromium#121]
![image](https://user-images.githubusercontent.com/20942887/58842799-5cb99180-86a2-11e9-960b-36cbb12317ce.png)

**Comment by summersir** [comment]
无论打开什么都不行 jjqqkk的和压缩包的都不行

**Comment by crystalYY** [comment]
我的也是

**Comment by bensk2001** [comment]
我的也是一样的错误提示
版本：Chromium-76.0.3800.0

**Comment by jjqqkk** [comment]
换新版 2.1
