### ISSUE TITLE
昨天还能用，今天就未连接到互联网

### ISSUE THREAD

**Issue by ukisssdh** [jjqqkk/chromium#123]
![360截图1872011888113120](https://user-images.githubusercontent.com/51391134/58928069-9adab200-8783-11e9-94a5-97ae2cafea64.png)

**Comment by ukisssdh** [comment]
打开关闭了很多次都不行

**Comment by gvc0461082002** [comment]
我也碰到了，可能要等等了

**Comment by ukisssdh** [comment]
好的，谢谢
 
------------------




 




------------------ 原始邮件 ------------------
发件人: "gvc0461082002"<notifications@github.com>; 
发送时间: 2019年6月5日(星期三) 中午11:30
收件人: "jjqqkk/chromium"<chromium@noreply.github.com>; 
抄送: "不想拥有太多情绪、"<842830119@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [jjqqkk/chromium] 昨天还能用，今天就未连接到互联网 (#123)



我也碰到了，可能要等等了

**Comment by freessrnet3vnet** [comment]
升级了就不能用了

**Comment by xzx1234** [comment]
怎么解决这个打不开问题

**Comment by ukisssdh** [comment]
有新的记得发我一份，谢谢

 




------------------ 原始邮件 ------------------
发件人: "xzx1234"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 晚上8:35
收件人: "jjqqkk/chromium"<chromium@noreply.github.com>;
抄送: "不想拥有太多情绪、"<842830119@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jjqqkk/chromium] 昨天还能用，今天就未连接到互联网 (#123)




怎么解决这个打不开问题

**Comment by anandes** [comment]
我今天也打不开了

**Comment by ukisssdh** [comment]
------------------




 




------------------ 原始邮件 ------------------
发件人: "anandes"<notifications@github.com>; 
发送时间: 2019年6月6日(星期四) 下午5:40
收件人: "jjqqkk/chromium"<chromium@noreply.github.com>; 
抄送: "不想拥有太多情绪、"<842830119@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [jjqqkk/chromium] 昨天还能用，今天就未连接到互联网 (#123)




我今天也打不开了
 
&mdash;

**Comment by jjqqkk** [comment]
下周更新 ip封了

**Comment by ukisssdh** [comment]
> 下周更新ip封了

干巴爹

**Comment by jjqqkk** [comment]
Back 😄 试试2.1.0
