### ISSUE TITLE
jjqqkk助手打不开chromium

### ISSUE THREAD

**Issue by lemonno2333** [jjqqkk/chromium#125]
![}(I)4TN1@2Y)5 S 8U5UHBY](https://user-images.githubusercontent.com/49359040/59003095-2ff2af00-8847-11e9-8bb2-e0a77ae8173f.png)

**Comment by jjqqkk** [comment]
windows版本

**Comment by lemonno2333** [comment]
Windows 1809

**Comment by jjqqkk** [comment]
@lemonno2333 试试2.1.0 刚刚发布

**Comment by nqxp** [comment]
> @lemonno2333 试试2.1.0 刚刚发布

最新的2.2.0也这样了
