### ISSUE TITLE
这个安装错误怎么处理

### ISSUE THREAD

**Issue by jasonhuizhang** [jjqqkk/chromium#128]
我在win7下安装提示这个错误有人知道吗?
"A network error occurred while attempting to read from the file:...."

**Comment by gdguan** [comment]
同情况，在两周之前一切正常；
在本周突然浏览器用不了，请作者查错谢谢。
假若本项目停止更新或维护，请作者向各位githuber们说明谢谢。
假若打扰了您，请您当做看不见本条信息，谢谢！

**Comment by jjqqkk** [comment]
ip被封了 大陆无法访问 只影响win 下周win版本有更新 mac可以正常用

**Comment by gdguan** [comment]
> ip被封了 大陆无法访问 只影响win 下周win版本有更新 mac可以正常用

谢谢

**Comment by jjqqkk** [comment]
新版来了 可以试试
