### ISSUE TITLE
jjqqkk安装时出现这个？？？

### ISSUE THREAD

**Issue by molimeng** [jjqqkk/chromium#129]
Could not write value JJQQKK to keySoftware Microsoft indowscurrentversion Run. Verifythat you have suficient access to that key, or contact yoursupport personnel

**Comment by jjqqkk** [comment]
安装JJQQKK需要管理员权限，windows登录账户需要在admin group里，大部分电脑装系统时创建的用户自动具有管理员权限，如果公司电脑有各种🚫，那只能😢
