### ISSUE TITLE
最近76.0.3806.1版本连接不畅啊

### ISSUE THREAD

**Issue by 43846582** [jjqqkk/chromium#131]
最近76.0.3806.1版本要反复开关启动好几次才能翻上墙，不知道是怎么回事

**Comment by Whalin-GitHub** [comment]
检查一下代理设置，本地局域网代理地址是否设置正确，建议开发人员自带脚本127.0.0.1:1080，这样可以方便小白使用。

**Comment by 43846582** [comment]
> 检查一下代理设置，本地局域网代理地址是否设置正确，建议开发人员自带脚本127.0.0.1:1080，这样可以方便小白使用。

不懂啊，下载来就用了，没有设置过，但是以前挺好的呀，最近几天才不好翻的

**Comment by jjqqkk** [comment]
用最新版JJQQKK
