### ISSUE TITLE
大哥，你们在封装的时候能不能封装进一个去广告插件啊

### ISSUE THREAD

**Issue by Drwonazy** [jjqqkk/chromium#132]
只要一个就好，现在是裸的，看油管三分钟就一个广告，我还一点办法都没有，烦人呢
大哥，你说呢

**Comment by Whalin-GitHub** [comment]
同求，虽然该浏览器自带翻墙功能，但是网页上无处不在的广告确实很烦人，而且又不支持安装扩展插件，最终导致不得不放弃使用该浏览器，希望开发人员至少放置一个广告拦截插件，比如Adblock Plus或AdGuard等市场上主流的广告拦截插件，这一点真的很重要。我相信开发人员不愿意加入广告拦截插件其原因是背后的利益链，但是如果因烦人的广告而被弃用，最终并不是一个双赢的选择，这一点还是希望开发人员以长远的发展眼光来看待此问题，重视用户体验。

**Comment by Whalin-GitHub** [comment]
推荐使用 Chromium 77.0.3819.0（开发者内部版本）支持安装扩展插件（拦截广告）,官方下载地址：https://download-chromium.appspot.com/，然后你在安装VPN扩展插件，同样可以实现带翻墙功能且拦截烦人广告还你一片清净的Chromoium浏览器，完全可以替代此处的版本，完全不用为烦人的广告而困扰。

**Comment by jjqqkk** [comment]
Google官方即将封杀所有ad-blocker，77之后只有企业付费开发者可以发布ad-blocker，let's wait and see..
