### ISSUE TITLE
电信网络下已经废了,尝试多少次都连不上了

### ISSUE THREAD

**Issue by songchaoyuan** [jjqqkk/chromium#133]
电信网络下已经废了,尝试多少次都连不上了

**Comment by Chrisjiajun** [comment]
我也是电信的 无法出去的世界 好压抑啊

**Comment by Whalin-GitHub** [comment]
鄙人也是中国电信，使用这里的Chromium浏览器不用开启小飞机就可以直接访问外网。估计你要检查一下你的本地局域网代理设置是否有设置为127.0.0.1，端口1080。没有设置的话无法访问外网。

**Comment by Chrisjiajun** [comment]
设置好就能用了~~谢谢~~么么哒~~

**Comment by jjqqkk** [comment]
本周发布更新，估计Tue/Wed

**Comment by Damsir** [comment]
> 鄙人也是中国电信，使用这里的Chromium浏览器不用开启小飞机就可以直接访问外网。估计你要检查一下你的本地局域网代理设置是否有设置为127.0.0.1，端口1080。没有设置的话无法访问外网。

这个怎么设置的，能详细点吗？

**Comment by jjqqkk** [comment]
欢迎测试新版JJQQKK，vpn和chromium两种方式都可
