### ISSUE TITLE
第一次更新后可以用再次要求更新后显示安装错误

### ISSUE THREAD

**Issue by 11810815XHN** [jjqqkk/chromium#135]
早上七点多更新后可用
重启后再次要求更新后一直安装失败
目前无法使用
请问怎么解决呢

**Comment by 11810815XHN** [comment]
重新下载后更新再次失败（mac）

**Comment by jjqqkk** [comment]
彻底删掉重装试试，从/Applications里删掉

**Comment by 11810815XHN** [comment]
谢谢，已经解决。
之前下载的JJQQKK如果是2.0.0版本下载安装后会要求更新，更新无法完成。
然后我直接下载了最新版本的2.1.0就可以直接使用了。
 
 
------------------ Original ------------------
