### ISSUE TITLE
windows的jjqqkk打开显示崩溃

### ISSUE THREAD

**Issue by amber06** [jjqqkk/chromium#137]
打开不了Windows的 求帮助

**Comment by jjqqkk** [comment]
用新版，刚刚发布

**Comment by amber06** [comment]
谢谢 ！




------------------ 原始邮件 ------------------
发件人: "JJQQKK"<notifications@github.com>; 
发送时间: 2019年6月12日(星期三) 晚上10:47
收件人: "jjqqkk/chromium"<chromium@noreply.github.com>; 
抄送: "AAM"<782362133@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [jjqqkk/chromium] windows的jjqqkk打开显示崩溃 (#137)




用新版，刚刚发布

**Comment by qouson** [comment]
2.4.0版也崩溃了
