### ISSUE TITLE
启动VPN出错

### ISSUE THREAD

**Issue by dreamjn** [jjqqkk/chromium#144]
安装TAP-Window出错，显示
an error occurred installing the tap device driver

**Comment by dreamjn** [comment]
我是win10 64位系统

**Comment by jjqqkk** [comment]
Win10登录账户有管理员权限吗

**Comment by jjqqkk** [comment]
@dreamjn 搞定了？ 🤔

**Comment by dreamjn** [comment]
应该是机器太旧了，驱动装不上，换了一台电脑就能装上了，但是 启动VPN 没反应，我看已经有人问了，就没再问
