### ISSUE TITLE
使用情况反馈

### ISSUE THREAD

**Issue by jkle112** [jjqqkk/chromium#150]
Chromium 76.0.3806.1，一直到这个版本，都是没有结构性变化，我直接解压复制给ChromiumPortable，放U盘，移动使用很安全，不会在使用过的计算机上留下痕迹。
之后的版本升级了，但是也导致无法内置VPN，没有办法变成便携版。
如果可以，希望以后升级可以保持原来的风格。
之前用的XX-Net也因为同样的改结构，导致无法再继续当个人升级便携版使用 ，只能重新找新的工具。
个人反馈不对请谅解。

**Comment by jjqqkk** [comment]
@jkle112 由于某种非技术原因 不再发布之前这种浏览器 这样可以帮助Chromium项目组和Google相关部门避免来自法律界莫名其妙的骚扰 采用JJQQKK这种外挂是目前平衡各方最好的产品形式
