### ISSUE TITLE
新版本的连接稳定不如旧版本

### ISSUE THREAD

**Issue by kanwoganma** [jjqqkk/chromium#151]
77.0.3824.6一次都没有连接成功过
76.0.3800.0能连上，但是不稳定，常常断开

**Comment by jjqqkk** [comment]
操作系统是啥

**Comment by i04lovemusic** [comment]
是直接下载浏览器使用吗？我之前单下浏览器也是这种情况，后来下载jjqqkk，在jjqqkk里启动chromium就每次启动都成功
