### ISSUE TITLE
最新的版本使用问题

### ISSUE THREAD

**Issue by li42899974** [jjqqkk/chromium#154]
新的版本是不是必须要求下载jjqqkk客户端，然后由客户端来打开浏览器，才能访问？
有没有另外一种方式呢？就像以前一样，直接打开浏览器就用？
因为单位安装了控制软件，不允许多个网卡，所以一打开vpn就断网了。
Windows是这样的，Mac好些，不存在这个问题！

**Comment by jjqqkk** [comment]
菜单里vpn/chromium二选一，都可以外网，用chromium不会启动网卡。以前的做法对Google Chromium项目组有一些潜在的负面影响，我们不会拿chromium声誉开玩笑的。用jjqqkk外挂可以绕开风险。
