### ISSUE TITLE
自动下载的2.20版本安装失败 一直让我retry

### ISSUE THREAD

**Issue by xyjump** [jjqqkk/chromium#155]
有没有解决办法呢 我是小白哈哈。。还有就是如果要卸载重新装的话 文件位置在哪

**Comment by jjqqkk** [comment]
有没有截图

**Comment by xyjump** [comment]
我现在在上班 晚上回家给你截图~




------------------ 原始邮件 ------------------
发件人: "JJQQKK"<notifications@github.com>;
发送时间: 2019年6月26日(星期三) 下午2:03
收件人: "jjqqkk/chromium"<chromium@noreply.github.com>;
抄送: "少年JUMP"<805752521@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jjqqkk/chromium] 自动下载的2.20版本安装失败 一直让我retry (#155)




有没有截图

**Comment by xyjump** [comment]
、
这就是安装截图了 麻烦你啦！




------------------ 原始邮件 ------------------
发件人: "JJQQKK"<notifications@github.com>;
发送时间: 2019年6月26日(星期三) 下午2:03
收件人: "jjqqkk/chromium"<chromium@noreply.github.com>;
抄送: "少年JUMP"<805752521@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jjqqkk/chromium] 自动下载的2.20版本安装失败 一直让我retry (#155)




有没有截图

**Comment by jjqqkk** [comment]
@xyjump 2.3刚刚发布 老的删干净了装新的试试 

windows: 控制面板里删掉jjqqkk
mac: 从应用里直接delete
