### ISSUE TITLE
mac一点击启动VPN就断网了

### ISSUE THREAD

**Issue by MasterElbow** [jjqqkk/chromium#157]
Chromium 77.0.3824.6
JJQQKK 2.3.0
接收都是接收了几百个字节就啥都没有了
跟手机开热点有关系吗？移动抓包了？

**Comment by jjqqkk** [comment]
mac通过手机热点上网？

**Comment by Damsir** [comment]
你好，我的也是，一启动VPN过一会就会断网，而且速度特别慢，是什么原因呀？

**Comment by jjqqkk** [comment]
@MasterElbow @Damsir 是中国大陆晚上时间段吗，记录一下时间

**Comment by Damsir** [comment]
白天，
<img width="491" alt="image" src="https://user-images.githubusercontent.com/16216553/60326346-19f68b00-99bc-11e9-8f6a-cc1ca7f77af1.png">

**Comment by jjqqkk** [comment]
看起来丢包严重 换个网络试试 直接wi-fi快不快

**Comment by Damsir** [comment]
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/16216553/60327456-722e8c80-99be-11e9-8950-99c39bd197af.png">
wifi也一样的

**Comment by jjqqkk** [comment]
DNS有问题？会不会改DNS? 

<img width="780" alt="Screen Shot 2019-06-28 at 9 33 56 PM" src="https://user-images.githubusercontent.com/45589513/60345839-7e314300-99ec-11e9-97d1-f879c1047fa0.png">

**Comment by Damsir** [comment]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/16216553/60347626-622fa080-99f0-11e9-95c7-27477142a1f8.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/16216553/60347642-6c519f00-99f0-11e9-8ccf-28dbc99e1b10.png">
这个地方改成你截图的三个吗？

**Comment by jjqqkk** [comment]
可以试一试 不保证成功 因为您的电脑居然有2个active network同时在跑 一般普通人的mac要么wi-fi 要么ethernet 我们的代码不一定能处理这种情况 为什么要同时用wi-fi和usb ethernet?
