### ISSUE TITLE
无法打开此安装程序包

### ISSUE THREAD

**Issue by gdguan** [jjqqkk/chromium#159]
没法打开此安装程序包。请与应用程序供应商联系,以确认这是个有效的windows install程序包。

**Comment by jjqqkk** [comment]
在处理这个问题 一部分用户报同样错误

**Comment by jjqqkk** [comment]
@gdguan 试试重新手工下载msi http://206.189.78.230/JJQQKK-2.3.0.msi

**Comment by Codeing-bing** [comment]
请问这个问题解决了么，我在使用中遇到这个问题了！


| |
xubingyc
|
|
xubingyc@163.com
|
签名由网易邮箱大师定制
在2019年6月29日 10:13，JJQQKK<notifications@github.com> 写道：

在处理这个问题 一部分用户报同样错误

**Comment by Codeing-bing** [comment]
试了，还是同样的错误提示


| |
xubingyc
|
|
xubingyc@163.com
|
签名由网易邮箱大师定制
在2019年6月29日 18:50，JJQQKK<notifications@github.com> 写道：

@gdguan 试试重新手工下载msi http://206.189.78.230/JJQQKK-2.3.0.msi
