### ISSUE TITLE
2.40安装失败

### ISSUE THREAD

**Issue by a1798636524** [jjqqkk/chromium#164]
![捕获](https://user-images.githubusercontent.com/33086354/60577861-c1a3fc80-9db2-11e9-878c-6c5194edc9bd.PNG)
如图所示一直提醒，经历了自动更新和手动卸载更新都不行，好像是安装包的问题？我是装着360的，应该不是他的问题吧

**Comment by dreamjn** [comment]
俺也一样

**Comment by jjqqkk** [comment]
很奇怪 手工下载一份 关掉管家软件 右键点msi，管理员权限启动 再不行就没办法了
