### ISSUE TITLE
JJQQKK 2.4版本 未上传最新win版本的Chromium

### ISSUE THREAD

**Issue by Whalin-GitHub** [jjqqkk/chromium#168]
在Win10上安装最新版本JJQQKK 2.4.0. msi之后，弹出自动升级Chromium的窗口，但是没有任何进度，应该是BUG。估计是没有上传win版本的Chromium，只上传了mac版本的 Chromium。希望尽快修复。

**Comment by lulu0426** [comment]
我也一样，进度条一直不动

**Comment by crystalYY** [comment]
2.4.0 window10 安装不上

**Comment by luoboju** [comment]
安装不了，怎么办

**Comment by jjqqkk** [comment]
building… 很快会同步到服务器
