### ISSUE TITLE
为什么我这个win10vpn连接上了，却上不了网，如果不打开vpn，单独打开浏览器，浏览器也连不上，求解！！

### ISSUE THREAD

**Issue by Seagant** [jjqqkk/chromium#175]
为什么我这个win10vpn连接上了，却上不了网，如果不打开vpn，单独打开浏览器，浏览器也连不上，求解！！

**Comment by lulu0426** [comment]
我也这样，估计是不能用了，以前速度还可以，现在网页都打不开了

**Comment by Seagant** [comment]
> 我也这样，估计是不能用了，以前速度还可以，现在网页都打不开了

关键我今儿来公司居然是能用的，难道跟网络有关系，我用的移动的，公司是联通的

**Comment by lulu0426** [comment]
还真有可能是网络的事，我的也是移动网，不过以前可以用的，现在不知道为什么不能用了

**Comment by Seagant** [comment]
> 还真有可能是网络的事，我的也是移动网，不过以前可以用的，现在不知道为什么不能用了

那我下班回家验证一下，看看是不是这样

**Comment by Seagant** [comment]
> 还真有可能是网络的事，我的也是移动网，不过以前可以用的，现在不知道为什么不能用了

兄弟，我刚才试了，连我们家联通的wifi就能连上。。。很神奇，速度也挺快

**Comment by lulu0426** [comment]
说明移动网墙的厉害，不过以前浏览器内置vpn的时候还能用，现在不行了，我用其他vpn有的能用有的不能用，并且速度不咋地

**Comment by jjqqkk** [comment]
和网络供应商有关 建议找个环境试试电信的宽带

**Comment by Seagant** [comment]
> 和网络供应商有关 建议找个环境试试电信的宽带

好的，谢谢！
