### ISSUE TITLE
启动jjkkqq会更改网络设置（win10无法使用）

### ISSUE THREAD

**Issue by ZHJIAB** [jjqqkk/chromium#176]
以前chromium的时候还可以使用，现在更新jjkkqq之后将其启动，它会自动修改网络IP和代理服务器，dns会被设置成最大的8.8.8.8，而ip地址和网关所在项都是空白，导致无法上网。

另外想请教的一个问题是，ISP的动态获取的dns服务器默认是怎么设置的？如果使用了公司或者学校自己的dns服务器，是不是就会导致chrome的vpn插件以及其他全局vpn软件无法使用用？

**Comment by ZHJIAB** [comment]
@jjqqkk

**Comment by jjqqkk** [comment]
通过JJQQKK启动Chromium不会改网络设置，只有启动vpn会改虚拟网卡地址，全局dns和网关，关闭vpn会恢复全局网关，但不会恢复dns。任何时候vpn都不会改物理网卡ip，否则根本无法连接vpn服务。

如果你发现物理网卡ip和网关都是空白，重启电脑看看没有启动vpn之前是什么状态，多试几次。一般情况下都是DHCP自动设定物理网卡，重启之后可以访问国内网，说明ip和网关都是对的。

命令行查ip和默认网关: 

netsh i i show ad
route print -4

不要从图形界面里查，windows这块有点问题。
