### ISSUE TITLE
windows10无法安装jjqqkk 

### ISSUE THREAD

**Issue by amber06** [jjqqkk/chromium#180]

**Comment by amber06** [comment]
显示 The installer has encountered an unexpected error installing this package.This may indicate a problem with this package. The error code is 2503.

**Comment by jjqqkk** [comment]
右键点.msi，用管理员权限安装试试看

**Comment by a1798636524** [comment]
> 右键点.msi，用管理员权限安装试试看

这种文件在WIN10里好像没法用管理员身份运行

**Comment by jjqqkk** [comment]
我们不清楚具体原因 右键管理员权限运行msi也是用户自己发现的解决方法 我们自己各种windows版本从未遇到msi无法安装的问题 可以试试从控制面板删除之前的版本 重新手工下载msi安装 或者下载其他国外软件的msi试试看 到底问题出在msi还是windows运行着某种服务阻止了安装

**Comment by Lang-Zh** [comment]
以管理员身份打开cmd命令提示符窗口 输入
msiexec /package C:\Users\Administrator\Desktop\JJQQKK-2.4.0.msi
