### ISSUE TITLE
win10 1903可以使用Chromium，但是启动VPN使用不了

### ISSUE THREAD

**Issue by qinghuan1998** [jjqqkk/chromium#183]
点击启动vpn后都打不开网页，更别说访问外网了，如果您知道处理方案，麻烦告知一下，谢谢。

**Comment by qinghuan1998** [comment]
会有显示这样的问题：
无法访问此网站 www.google.com.hk 的响应时间过长。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_TIMED_OUT

**Comment by Mingcheng11** [comment]
我也是跟你一样，升级1903版后一开启VPN自动断网。从windows设置里恢复上一个版本就好了

**Comment by qinghuan1998** [comment]
> 我也是跟你一样，升级1903版后一开启VPN自动断网。从窗口设置里恢复上一个版本就好了

原来不是特例问题啊，可是1903  更新了好久才更新完。。有点难受
