### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by outlier009** [jjqqkk/chromium#19]
打开后刚刚进入页面就闪退，试了几次都是。我的系统是64位win10.

**Comment by younglifestyle** [comment]
我也是win10，没出现你这个现象，你要不重新试试

**Comment by GaranYeon** [comment]
强退

**Comment by outlier009** [comment]
刚刚又试了试，用了最近的2个版本都闪退。

**Comment by xq773939719** [comment]
MacOS10.13.6版闪退

**Comment by free-vpn** [comment]
windows请运行命令“winver"看windows版本，比如1709， 1803。。 发过来 谢谢

**Comment by free-vpn** [comment]
@xq773939719 every time?

**Comment by GaranYeon** [comment]
win7旗舰64bit
版本6.1（内部版本7601：sp1）

**Comment by ysbreh** [comment]
@free-vpn 怎么添加自己的服务器

**Comment by joshatt** [comment]
从69升级到70版, 再试, 3分钟后闪退:
......
[0926/112600.136:ERROR:registration_protocol_win.cc(56)] CreateFile: 系统找不到指定的文件。 (0x2)
[0926/112703.512:ERROR:crashpad_client_win.cc(130)] crash server failed to launch, self-terminating

**Comment by xq773939719** [comment]
> @xq773939719 every time?

是的，出现新标签就会卡退

**Comment by qiaojiang** [comment]
点击打开新页面“+”，闪退。win10

**Comment by itnewgay** [comment]
还是建议使用chrome稳定版本吧。 闪退情况太多了

**Comment by xcger** [comment]
怎么升级freeVPN里的chromium版本呢？
