### ISSUE TITLE
浏览器崩溃

### ISSUE THREAD

**Issue by dasdawd** [jjqqkk/chromium#193]
![KFAU4WEW}C8P1_BKF%%5T2M](https://user-images.githubusercontent.com/54176900/63167612-5fead980-c064-11e9-9c7b-12a7e97d18f6.png)
78.0.3880.4版本的

**Comment by jackwu882002** [comment]
同样问题 苹果电脑 mac的10.15beta 更新后无法打开浏览器，请修正，谢谢。

**Comment by olko2018** [comment]
> 同样问题 苹果电脑 mac的10.15beta 更新后无法打开浏览器，请修正，谢谢。



> ![KFAU4WEW}C8P1_BKF%%5T2M](https://user-images.githubusercontent.com/54176900/63167612-5fead980-c064-11e9-9c7b-12a7e97d18f6.png)
> 78.0.3880.4版本的

Install VC + + 2017 & VC + + 2015

**Comment by olko2018** [comment]
分かりました

来自 Outlook<http://aka.ms/weboutlook>
________________________________
发件人: JJQQKK <notifications@github.com>
发送时间: 2019年11月29日 6:55
收件人: jjqqkk/chromium <chromium@noreply.github.com>
抄送: olko2018 <yoooooo2018@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [jjqqkk/chromium] 浏览器崩溃 (#193)


Closed #193<https://github.com/jjqqkk/chromium/issues/193>.

―
