### ISSUE TITLE
Mac打开vpn，关闭chromium后会自动再次启动chromium

### ISSUE THREAD

**Issue by houxiao888** [jjqqkk/chromium#201]
Mac打开vpn，关闭chromium后会自动再次启动chromium。
另外，chromium里的广告页关闭后也会自动再次打开。关闭vpn后chromium也同时自己关掉了...
求问是什么情况，有点方o(╥﹏╥)o~

**Comment by HelloDylan** [comment]
同样的问题。。。放弃了。。。
