### ISSUE TITLE
这什么意思 更新以后 https://www.freevpn.pw/zh-cn/?  这网页一直跳 关不掉！

### ISSUE THREAD

**Issue by lidanlei** [jjqqkk/chromium#202]
求解决 ！

**Comment by l3125831q** [comment]
应该是强制广告吧，吃相不大好哇

**Comment by hzsrc** [comment]
这样搞已经基本没法用了啊，赶快撤了吧

**Comment by jasonWangsk** [comment]
> `求优化，感觉像病毒__`

**Comment by hzsrc** [comment]
第一次chrome出来显示为一个广告页可以接受，毕竟作者项目也需要资金来支撑。但这样不停的周期性弹出，就难以接受了

**Comment by Nsir15** [comment]
附议

**Comment by kuyuepo** [comment]
强力要求控制 https://www.freevpn.pw/zh-cn/?这个弹出次数，感觉中病毒了。适当广告是可以接受的，你现在过分了啊

**Comment by mukeyeshen** [comment]
可以用其他vpn 何必死一家

kuyuepo <notifications@github.com> 于2019年9月18日周三 下午11:55写道：

**Comment by om0504** [comment]
2.5.0直接被公司防毒報病毒了，這種永遠關不掉的方式已經是強x用戶的行為了。。。
是該找找別家VPN了

**Comment by Buccaneer01** [comment]
的确和病毒一样，强制打开，这就比较过了

**Comment by Mercy08042** [comment]
> 第一次chromium出来显示为一个广告页可以接受，毕竟作者项目也需要资金来支撑。但这样不停的周期性弹出，就难以接受了

可以固定标签哦

**Comment by 68891191** [comment]
你们真的很搞笑，明明就是免费用，还要求一大堆，而且这个标签页明明也可以不用管他，自己新建标签页就好了。

**Comment by crystalYY** [comment]
支持作者，只要不关了那个tag页面就行，作者很良心的在做软件，还要忍受骂名，真是搞不懂你们

**Comment by hzsrc** [comment]
自动更新后已经好了，感谢作者！建议chromium弹出来时直接显示为一个广告页！
