### ISSUE TITLE
不能切換輸入法

### ISSUE THREAD

**Issue by om0504** [jjqqkk/chromium#205]
用jjqqkk安裝的chromium時，沒辦法切換輸入法，只能用英文。
要搜索只能用copy paste

win10 x64, 1809
jjqqkk : 2.4.0, 2.5.0皆有此問題
Chromium : 78.0.3902.4
輸入法 : 微軟注音輸入法 (ㄅ半)，非新注音

**Comment by om0504** [comment]
請問回答了什麼就closed了?

**Comment by jjqqkk** [comment]
![1](https://user-images.githubusercontent.com/45589513/70048906-5fbc1d00-1606-11ea-97fc-bf3780abef2c.jpg)
![2](https://user-images.githubusercontent.com/45589513/70048910-60ed4a00-1606-11ea-9d17-1affd4863243.jpg)

sorry... 实在。。实在。。是无法回答

**Comment by om0504** [comment]
喔，沒事，您可以直接說沒辦法解就好了，沒事的，謝謝您。我只是以為我漏看啥就被關了。。。

**Comment by jjqqkk** [comment]
@om0504 sorry for the trouble 😅
