### ISSUE TITLE
更新之后就上不了网了

### ISSUE THREAD

**Issue by darksider117** [jjqqkk/chromium#208]
试了能想到的所有方法都没用，请尽快修复

**Comment by quchunguang** [comment]
同上。更新至2.5.1后，VPN页也不弹了，所有网站上不去。

**Comment by scfmxx** [comment]
同上。更新至2.5.1后，只弹出一个谷歌搜索网页，再也没有出现VPN页面，所有的网站都上不去了，鼓捣了一天，反复卸载安装数次无效。老版本不能安装，说windows无法打开该程序。
