### ISSUE TITLE
更新之后打开方式不再是FREEVPN而是之前的网页，然后就无法再联网了

### ISSUE THREAD

**Issue by klevic** [jjqqkk/chromium#209]
更新之后打开方式不再是FREEVPN而是之前的网页，然后就无法再联网了

**Comment by zrgalj** [comment]
都一样了 ，不知道在没在解决呢

**Comment by Sophanatprime** [comment]
9月16号开始挂了好多VPN，QAQ

**Comment by Kuzmacosmos** [comment]
什么网站都进不去

**Comment by klevic** [comment]
> 都一样了，不知道在没在解决呢

现在是回复FREEVPN页面，但是还是连不上网

**Comment by Kuzmacosmos** [comment]
> > 都一样了，不知道在没在解决呢
> 
> 现在是回复FREEVPN页面，但是还是连不上网

我的连freevpn页面都没有，只有一个new tab

**Comment by klevic** [comment]
> > > 都一样了，不知道在没在解决呢
> > 
> > 
> > 现在是回复FREEVPN页面，但是还是连不上网
> 
> 我的连freevpn页面都没有，只有一个新标签

我昨天都还能进得去。只是在没有更新的情况下。

**Comment by Kuzmacosmos** [comment]
> > > > 都一样了，不知道在没在解决呢
> > > 
> > > 
> > > 现在是回复FREEVPN页面，但是还是连不上网
> > 
> > 
> > 我的连freevpn页面都没有，只有一个新标签
> 
> 我昨天都还能进得去。只是在没有更新的情况下。

我昨天更完就进不去了

**Comment by klevic** [comment]
> > > > > 都一样了，不知道在没在解决呢
> > > > 
> > > > 
> > > > 现在是回复FREEVPN页面，但是还是连不上网
> > > 
> > > 
> > > 我的连freevpn页面都没有，只有一个新标签
> > 
> > 
> > 我昨天都还能进得去。只是在没有更新的情况下。
> 
> 我昨天更完就进不去了

作者应该在解决了吧，最近好像某有关部门在严打VPN的事情

**Comment by tinycooper** [comment]
跟新后启动不了V-N

**Comment by zhs100072** [comment]
现在国内的梯子是不是都被拆了，，已经失联了，，所有VPN都失效了。

**Comment by Kuzmacosmos** [comment]
> 现在国内的梯子是不是都被拆了，，已经失联了，，所有VPN都失效了。

看后天

**Comment by 68891191** [comment]
希望作者 平安

**Comment by peterhuang3** [comment]
回到老版本是否能上啊，去哪里下载老版本啊

**Comment by Kuzmacosmos** [comment]
> 回到老版本是否能上啊，去哪里下载老版本啊

我试了一下2.5的，不行

**Comment by peterhuang3** [comment]
> 希望作者 平安

作者在伦敦

**Comment by peterhuang3** [comment]
> > 回到老版本是否能上啊，去哪里下载老版本啊
> 
> 我试了一下2.5的，不行

你有其他的Mac版的VPN吗

**Comment by Kuzmacosmos** [comment]
> > > 回到老版本是否能上啊，去哪里下载老版本啊
> > 
> > 
> > 我试了一下2.5的，不行
> 
> 你有其他的Mac版的VPN吗

抱歉，我没有:(
以前在win上装过ss，后来电脑坏了换mac就一直用的这

**Comment by peterhuang3** [comment]
> > > > 回到老版本是否能上啊，去哪里下载老版本啊
> > > 
> > > 
> > > 我试了一下2.5的，不行
> > 
> > 
> > 你有其他的Mac版的VPN吗
> 
> 抱歉，我没有:(
> 以前在win上装过ss，后来电脑坏了换mac就一直用的这

哦，好吧，谢谢

**Comment by Kuzmacosmos** [comment]
> > > > > 回到老版本是否能上啊，去哪里下载老版本啊
> > > > 
> > > > 
> > > > 我试了一下2.5的，不行
> > > 
> > > 
> > > 你有其他的Mac版的VPN吗
> > 
> > 
> > 抱歉，我没有:(
> > 以前在win上装过ss，后来电脑坏了换mac就一直用的这
> 
> 哦，好吧，谢谢

看后天有没有什么进展，明天是那个week的最后一天

**Comment by peterhuang3** [comment]
> > > > > > 回到老版本是否能上啊，去哪里下载老版本啊
> > > > > 
> > > > > 
> > > > > 我试了一下2.5的，不行
> > > > 
> > > > 
> > > > 你有其他的Mac版的VPN吗
> > > 
> > > 
> > > 抱歉，我没有:(
> > > 以前在win上装过ss，后来电脑坏了换mac就一直用的这
> > 
> > 
> > 哦，好吧，谢谢
> 
> 看后天有没有什么进展，明天是那个week的最后一天

“那个week”？

**Comment by peterhuang3** [comment]
> > > > > > > 回到老版本是否能上啊，去哪里下载老版本啊
> > > > > > 
> > > > > > 
> > > > > > 我试了一下2.5的，不行
> > > > > 
> > > > > 
> > > > > 你有其他的Mac版的VPN吗
> > > > 
> > > > 
> > > > 抱歉，我没有:(
> > > > 以前在win上装过ss，后来电脑坏了换mac就一直用的这
> > > 
> > > 
> > > 哦，好吧，谢谢
> > 
> > 
> > 看后天有没有什么进展，明天是那个week的最后一天
> 
> “那个week”？

如果是因为“网安周”，那么16号-20号上午都没事啊！

**Comment by peterhuang3** [comment]
> > > > > > 回到老版本是否能上啊，去哪里下载老版本啊
> > > > > 
> > > > > 
> > > > > 我试了一下2.5的，不行
> > > > 
> > > > 
> > > > 你有其他的Mac版的VPN吗
> > > 
> > > 
> > > 抱歉，我没有:(
> > > 以前在win上装过ss，后来电脑坏了换mac就一直用的这
> > 
> > 
> > 哦，好吧，谢谢
> 
> 看后天有没有什么进展，明天是那个week的最后一天



> > > > > > 回到老版本是否能上啊，去哪里下载老版本啊
> > > > > 
> > > > > 
> > > > > 我试了一下2.5的，不行
> > > > 
> > > > 
> > > > 你有其他的Mac版的VPN吗
> > > 
> > > 
> > > 抱歉，我没有:(
> > > 以前在win上装过ss，后来电脑坏了换mac就一直用的这
> > 
> > 
> > 哦，好吧，谢谢
> 
> 看后天有没有什么进展，明天是那个week的最后一天

如果是因为“网安周”，那么16号-20号上午都没事啊！

**Comment by Kuzmacosmos** [comment]
> > > > > > > 回到老版本是否能上啊，去哪里下载老版本啊
> > > > > > 
> > > > > > 
> > > > > > 我试了一下2.5的，不行
> > > > > 
> > > > > 
> > > > > 你有其他的Mac版的VPN吗
> > > > 
> > > > 
> > > > 抱歉，我没有:(
> > > > 以前在win上装过ss，后来电脑坏了换mac就一直用的这
> > > 
> > > 
> > > 哦，好吧，谢谢
> > 
> > 
> > 看后天有没有什么进展，明天是那个week的最后一天
> 
> > > > > > > 回到老版本是否能上啊，去哪里下载老版本啊
> > > > > > 
> > > > > > 
> > > > > > 我试了一下2.5的，不行
> > > > > 
> > > > > 
> > > > > 你有其他的Mac版的VPN吗
> > > > 
> > > > 
> > > > 抱歉，我没有:(
> > > > 以前在win上装过ss，后来电脑坏了换mac就一直用的这
> > > 
> > > 
> > > 哦，好吧，谢谢
> > 
> > 
> > 看后天有没有什么进展，明天是那个week的最后一天
> 
> 如果是因为“网安周”，那么16号-20号上午都没事啊！

只能说有这个概率。具体怎么操作的就真的不知道了

**Comment by peterhuang3** [comment]
> > > > > > > > 回到老版本是否能上啊，去哪里下载老版本啊
> > > > > > > 
> > > > > > > 
> > > > > > > 我试了一下2.5的，不行
> > > > > > 
> > > > > > 
> > > > > > 你有其他的Mac版的VPN吗
> > > > > 
> > > > > 
> > > > > 抱歉，我没有:(
> > > > > 以前在win上装过ss，后来电脑坏了换mac就一直用的这
> > > > 
> > > > 
> > > > 哦，好吧，谢谢
> > > 
> > > 
> > > 看后天有没有什么进展，明天是那个week的最后一天
> > 
> > 
> > > > > > > > 回到老版本是否能上啊，去哪里下载老版本啊
> > > > > > > 
> > > > > > > 
> > > > > > > 我试了一下2.5的，不行
> > > > > > 
> > > > > > 
> > > > > > 你有其他的Mac版的VPN吗
> > > > > 
> > > > > 
> > > > > 抱歉，我没有:(
> > > > > 以前在win上装过ss，后来电脑坏了换mac就一直用的这
> > > > 
> > > > 
> > > > 哦，好吧，谢谢
> > > 
> > > 
> > > 看后天有没有什么进展，明天是那个week的最后一天
> > 
> > 
> > 如果是因为“网安周”，那么16号-20号上午都没事啊！
> 
> 只能说有这个概率。具体怎么操作的就真的不知道了

哎~好吧😌

**Comment by peterhuang3** [comment]
各位，Chromium已解封，同时广告也没有了！

**Comment by Kuzmacosmos** [comment]
> 各位，Chromium已解封，同时广告也没有了！

实测可用😂

**Comment by 68891191** [comment]
> 各位，Chromium已解封，同时广告也没有了！

感谢告知，其实我觉得那个真的不算什么广告，自己新建一个标签页 就完全不影响使用了。

**Comment by Blue-Toy** [comment]
https://www.freevpn.pw/zh-cn/  输入这个网址，我是雷锋

**Comment by peterhuang3** [comment]
> > 各位，Chromium已解封，同时广告也没有了！
> 
> 感谢告知，其实我觉得那个真的不算什么广告，自己新建一个标签页 就完全不影响使用了。

🤟

**Comment by WrathGluttony** [comment]
> 各位，Chromium已解封，同时广告也没有了！

①请问是Mac版chromium还是Windows版chromium已解封?
②Windows版的JJQQKK2.5.1里的Chromium可以正常科学上网了吗?
③下载单文件版的Windows版Chromium最新版zip格式的压缩包(Chromium-windows-78.0.3904.9.zip)到本地,然后解压缩就可以用了吗?
④我这里用JJQQKK2.5.1和Chromium-windows-78.0.3904.9.zip单文件解压后,都不能科学上网,你们那里是怎么能正常科学上网的?
⑤请详细指点一下,谢谢您,bow

**Comment by peterhuang3** [comment]
> https://www.freevpn.pw/zh-cn/ 输入这个网址，我是雷锋

> > 各位，Chromium已解封，同时广告也没有了！
> 
> ①请问是Mac版chromium还是Windows版chromium已解封?
> ②Windows版的JJQQKK2.5.1里的Chromium可以正常科学上网了吗?
> ③下载单文件版的Windows版Chromium最新版zip格式的压缩包(Chromium-windows-78.0.3904.9.zip)到本地,然后解压缩就可以用了吗?
> ④我这里用JJQQKK2.5.1和Chromium-windows-78.0.3904.9.zip单文件解压后,都不能科学上网,你们那里是怎么能正常科学上网的?
> ⑤请详细指点一下,谢谢您,bow

Mac版亲测可用，Windows版不清楚！
下载，解压，直接双击即可！JJQQKK只是多了一个自动更新而已！

**Comment by zhs100072** [comment]
这个网站已经打不开很久了，我是win10，JJQQKK已经不能爬墙了。





------------------ 原始邮件 ------------------
发件人: "peterhuang3"<notifications@github.com>;
发送时间: 2019年9月22日(星期天) 晚上8:30
收件人: "jjqqkk/chromium"<chromium@noreply.github.com>;
抄送: "李龚哲"<724826278@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [jjqqkk/chromium] 更新之后打开方式不再是FREEVPN而是之前的网页，然后就无法再联网了 (#209)



 
https://www.freevpn.pw/zh-cn/ 输入这个网址，我是雷锋
    
各位，Chromium已解封，同时广告也没有了！
  
①请问是Mac版chromium还是Windows版chromium已解封?
 ②Windows版的JJQQKK2.5.1里的Chromium可以正常科学上网了吗?
 ③下载单文件版的Windows版Chromium最新版zip格式的压缩包(Chromium-windows-78.0.3904.9.zip)到本地,然后解压缩就可以用了吗?
 ④我这里用JJQQKK2.5.1和Chromium-windows-78.0.3904.9.zip单文件解压后,都不能科学上网,你们那里是怎么能正常科学上网的?
 ⑤请详细指点一下,谢谢您,bow
  
Mac版亲测可用，Windows版不清楚！
 下载，解压，直接双击即可！JJQQKK只是多了一个自动更新而已！

**Comment by klevic** [comment]
> 各位，铬已解封，同时广告也没有了！

我这里好像还是打不开，连不上网？你们是可以直接翻了？

**Comment by peterhuang3** [comment]
> > 各位，铬已解封，同时广告也没有了！
> 
> 我这里好像还是打不开，连不上网？你们是可以直接翻了？

是的，Mac版亲测可用，Windows版不清楚！

**Comment by joycaf** [comment]
win10可以用，启用vpn就行了啊

**Comment by WrathGluttony** [comment]
谢谢您的回复,我是Win7 64位旗舰版SP1,右击JJQQKK任务栏图标,点击vpn后,是启动了,但是所有联网的软件都断网了,什么软件都上不了网了,是不是还需要进行其它配置?直接点击JJQQKK里的VPN就行了?不需要进行其它的设置?打搅了


| |
请比我幸福
|
|
pure1320@163.com
|
签名由网易邮箱大师定制
在2019年9月23日 09:29，joycaf<notifications@github.com> 写道：

win10可以用，启用vpn就行了啊

**Comment by joycaf** [comment]
> 谢谢您的回复,我是Win7 64位旗舰版SP1,右击JJQQKK任务栏图标,点击vpn后,是启动了,但是所有联网的软件都断网了,什么软件都上不了网了,是不是还需要进行其它配置?直接点击JJQQKK里的VPN就行了?不需要进行其它的设置?打搅了 | | 请比我幸福 | | pure1320@163.com | 签名由网易邮箱大师定制 在2019年9月23日 09:29，joycaf<notifications@github.com> 写道： win10可以用，启用vpn就行了啊 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

我是直接点启用就好了，其他浏览器也可以翻。没启用只打开谷歌浏览器是不行的

**Comment by lefantian** [comment]
最新2.5.1启动vpn以后目前可以科学了

**Comment by klevic** [comment]
> > > 各位，铬已解封，同时广告也没有了！
> > 
> > 
> > 我这里好像还是打不开，连不上网？你们是可以直接翻了？
> 
> 是的，Mac版亲测可用，Windows版不清楚！

**Comment by klevic** [comment]
> > > 各位，铬已解封，同时广告也没有了！
> > 
> > 
> > 我这里好像还是打不开，连不上网？你们是可以直接翻了？
> 
> 是的，Mac版亲测可用，Windows版不清楚！

已经好了，可以直接使用了，不用开VPN也可以

**Comment by WrathGluttony** [comment]
> > > > 各位，铬已解封，同时广告也没有了！
> > > 
> > > 
> > > 我这里好像还是打不开，连不上网？你们是可以直接翻了？
> > 
> > 
> > 是的，Mac版亲测可用，Windows版不清楚！
> 
> 已经好了，可以直接使用了，不用开VPN也可以
①我是Win7 64位旗舰版SP1,我这里右击JJQQKK任务栏图标,点击Chromium后,什么网页也打不开,都是显示"喔唷,崩溃啦!显示此网页时出了点问题,了解详情"
②用第二种方法,就是右击JJQQKK任务栏图标,左击"启动VPN",提示VPN已开启,但是之后网直接就断了,所有的软件都上不了网了,请问我哪里设置不对?还需要额外的设置吗?我看有网友说开启VPN后,是虚拟出1个网卡?还是电脑不能有两个网络设备?请问开启JJQQKK的VPN,还需要进行额外的其它设置吗?
