### ISSUE TITLE
只要新建页面就会闪退

### ISSUE THREAD

**Issue by AromanRon** [jjqqkk/chromium#21]
win10 64最新

**Comment by qq159217** [comment]
我也遇到这个问题了,刚开始很稳定,之后新开就有点闪退,网速很好,很棒

**Comment by SkyGrass** [comment]
我之前也遇到过，我删除了某个拓展之后，就不会闪退了！

**Comment by wuyow** [comment]
我在WIN10 64位使用这个，并未出现此现象，或许是你的系统有问题吧^^
