### ISSUE TITLE
安装的时候显示 指定账户已存在？

### ISSUE THREAD

**Issue by xyjump** [jjqqkk/chromium#211]
![Uploading QQ图片20190924085739.png…]()

**Comment by zickzack1992** [comment]
需要卸载干净才能安装

**Comment by xyjump** [comment]
感谢！用360软件卸载了重新安装就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zickzack1992"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月24日(星期二) 中午12:01
收件人:&nbsp;"jjqqkk/chromium"<chromium@noreply.github.com&gt;;
抄送:&nbsp;"少年JUMP"<805752521@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jjqqkk/chromium] 安装的时候显示 指定账户已存在？ (#211)




需要卸载干净才能安装
