### ISSUE TITLE
如何卸载？和安装时"指定账户已存在"

### ISSUE THREAD

**Issue by ishihara2333** [jjqqkk/chromium#223]
删了文件加后再次安装提示”指定账户已存在“

**Comment by zickzack1992** [comment]
控制面板-程序和功能-“JJQQKK”+“TAP-WINDOWS”都卸载了，才能重装

**Comment by OUCTheoryGroup** [comment]
如要选择 “启动VPN” 时无反应呢？是咋回事？

**Comment by ishihara2333** [comment]
> 控制面板 - 程序和功能 - “JJQQKK” +“TAP-WINDOWS”都卸载了，才能重装

谢谢 可是我控制面板没有这两样QAQ 想问一下还能怎么办

**Comment by ishihara2333** [comment]
> 控制面板 - 程序和功能 - “JJQQKK” +“TAP-WINDOWS”都卸载了，才能重装

谢谢，可是我程序和功能中没有这两样，现在要怎么才能卸载？

**Comment by zickzack1992** [comment]
> > 控制面板 - 程序和功能 - “JJQQKK” +“TAP-WINDOWS”都卸载了，才能重装
> 
> 谢谢，可是我程序和功能中没有这两样，现在要怎么才能卸载？

那我就不知道了，之前我就是这样弄的，现在好像都上不去了，反正我这边打不开网页

**Comment by ishihara2333** [comment]
> > > 控制面板-程序和功能-“ JJQQKK” +“ TAP-WINDOWS”都卸载了，才能重装
> > 
> > 
> > 谢谢，可是我程序和功能中没有这两样，现在要怎么才能卸载？
> 
> 那我就不知道了，之前我就是这样弄的，现在好像都上不去了，反正我这边打不开网页

好的，谢谢了
