### ISSUE TITLE
虽然我觉得这么说不好,不过我还是要问问有没有其他vpn推荐

### ISSUE THREAD

**Issue by xueming-xing** [jjqqkk/chromium#224]

**Comment by luyouyeah** [comment]
有，你留下邮箱我来找你

**Comment by qq1924036133** [comment]
> 有，你留下邮箱我来找你
1924036133@qq.com 万分感谢

**Comment by liuhongwei2018** [comment]
648699552@qq.com   谢谢

**Comment by sam119** [comment]
> 有，你留下邮箱我来找你

pdvnzdl@163.com 谢谢

**Comment by zcrabbit** [comment]
383623573@qq.com 谢谢

**Comment by zcrabbit** [comment]
> 有，你留下邮箱我来找你

383623573@qq.com

**Comment by asc1236969** [comment]
757236892@qq.com

**Comment by lonelyhammer** [comment]
longs99@163.com  谢谢

**Comment by LCB14** [comment]
1642272412@qq.com 谢谢

**Comment by jiyanghe** [comment]
hjyyeah@163.com 万分感谢

**Comment by citrusyahello** [comment]
> 有，你留下邮箱我来找你

957545388@qq.com 感谢！

**Comment by momi0099** [comment]
> 有，你留下邮箱我来找你

798875223@qq,com  麻烦大佬了~~

**Comment by wangxiaolei1987** [comment]
wangxiaolei1987@outlook.com 谢谢大佬分享

**Comment by wangxiaolei1987** [comment]
@luyouyeah

**Comment by luyouyeah** [comment]
我打算搞個QQ群來交流，或者是搞某個網絡聊天室，你們表態 @xueming-xing @qq1924036133 @liuhongwei2018 @sam119

**Comment by asc1236969** [comment]
qq群

**Comment by qq1924036133** [comment]
可以呀 qq群挺好:)



------------------ 原始邮件 ------------------
发件人: "luyouyeah"<notifications@github.com>; 
发送时间: 2019年10月2日(星期三) 下午4:40
收件人: "jjqqkk/chromium"<chromium@noreply.github.com>; 
抄送: "Sillyforceman"<1924036133@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [jjqqkk/chromium] 虽然我觉得这么说不好,不过我还是要问问有没有其他vpn推荐 (#224)




我打算搞個QQ群來交流，或者是搞某個網絡聊天室，你們表態 @xueming-xing @qq1924036133 @liuhongwei2018 @sam119

**Comment by mr-jxy** [comment]
大佬 求个能看视频的vpn 614272658@qq.com

**Comment by wangxiaolei1987** [comment]
qq群 不好，容易被举报。

**Comment by luyouyeah** [comment]
我剛剛生申請了一個30天的網絡聊天空間，你們進來啊討論啊
網址是[點這裡啊啊](https://vpn-chat.rocket.chat)

**Comment by luoxw2016** [comment]
jmdxlxw@163.com，谢谢

**Comment by xueming-xing** [comment]
> 有，你留下邮箱我来找你

15717672622@163.com  谢了

**Comment by jason19910825** [comment]
891753830@qq.com 谢谢

**Comment by dingyr** [comment]
> 有，你留下邮箱我来找你

7387223350@qq.com 感谢

**Comment by dingyr** [comment]
> 有，你留下邮箱我来找你

738723350@qq.com 感谢

**Comment by 1647357894** [comment]
1647357894@qq.com谢啦

**Comment by luyouyeah** [comment]
我剛剛生申請了一個30天的網絡聊天空間，你們進來啊討論啊
網址是https://vpn-chat.rocket.chat

**Comment by yawudede** [comment]
10500696552qq.com 求大佬分享

**Comment by qiusister** [comment]
[蚂蚁加速器可以顶一阵](https://ant.antss026.com/aff/8tjX)，这个玩意儿可以暂时顶一下。不过觉得还是觉得这个好一点，如果这个正常的话。

**Comment by tb8212** [comment]
tb8212@live.cn谢谢大佬

**Comment by lkm2222** [comment]
> 
> 
> 有，你留下邮箱我来找你

616343014@qq.com. thx~

**Comment by weigls** [comment]
weiglx@163.com 求带。谢谢。

**Comment by bb610817338** [comment]
cwj610817338@qq.com  感谢大佬

**Comment by peterhuang3** [comment]
又可以连接了~~~

**Comment by 68891191** [comment]
钓鱼贴么。。。留邮箱的 全部充军（手动滑稽）

**Comment by summersir** [comment]
shenjc1992@foxmail.com   感谢大佬

**Comment by luyouyeah** [comment]
沒想到這麼多人

**Comment by hsoul** [comment]
> 有，你留下邮箱我来找你

hsoulqing@126.com

**Comment by w657395940** [comment]
w657395940@163.com

**Comment by luoshupeng** [comment]
shupengluo@gmail.com

**Comment by Clident** [comment]
729220667@qq.com 谢谢

**Comment by Chet-D-family** [comment]
chet.d.family@gmail.com
谢谢。

**Comment by youyou135159** [comment]
> 有，你留下邮箱我来找你

1625202275@qq.com
3q

**Comment by tenderhooligan** [comment]
可以蹲一个吗？

**Comment by Chet-D-family** [comment]
..???

tenderhooligan <notifications@github.com>于2019年10月9日 周三15:02写道：

**Comment by userKD** [comment]
470446265@qq.com  感谢大佬

**Comment by weidadaGG** [comment]
> 有，你留下邮箱我来找你

15724747247@163.com 感谢大佬

**Comment by wanlideid** [comment]
1033241857@qq.com 感谢大佬

**Comment by wanlideid** [comment]
> 有，你留下邮箱我来找你

1033241857@qq.com 感谢大佬

**Comment by pyhuxiaoyin** [comment]
3051482463@qq.com 感谢大佬

**Comment by wanglyu** [comment]
2484094761@qq.com 感谢大佬

**Comment by yyuanl** [comment]
> 有，你留下邮箱我来找你

1092068432@qq.com跪谢大佬

**Comment by xxedts** [comment]
> 有，你留下邮箱我来找你

xxedts@icloud.com ，感谢大佬

**Comment by simonnoyi** [comment]
fanqiangtogoole@gmail.com，感谢大佬

**Comment by shourds** [comment]
2734243102@qq.com谢谢

**Comment by lKKLKLK** [comment]
lkiyyu@163.com感谢大佬

**Comment by sunwenmeng** [comment]
13110071255@163.com

**Comment by Nicholas-Tiezhu** [comment]
1757553827@qq.com 谢谢大佬

**Comment by shophiecho** [comment]
805857787@qq.com 谢谢大佬

**Comment by withzuoyou** [comment]
1209898943@qq.com  谢谢大佬

**Comment by qingyuangweil** [comment]
1414325602@qq.com   谢谢大佬

**Comment by wujinfeng007** [comment]
linalinatmd@163.com  Thanks ! 感谢！

**Comment by w1072337359** [comment]
1072337359@qq.com

**Comment by dengbotao001** [comment]
243083776@qq.com谢谢大佬

**Comment by w1072337359** [comment]
> 有，你留下邮箱我来找你

1072337359@qq.com

**Comment by lkm2222** [comment]
FKHW9012251@163.com
