### ISSUE TITLE
今天已经满血复活了！

### ISSUE THREAD

**Issue by Litangren** [jjqqkk/chromium#226]
连续几天失效，VPN今天已经满血复活了！很好用！感谢作者！

**Comment by momi0099** [comment]
中午过后又连不上了……作者大佬抽空再修复下吧……

**Comment by mimixingzhe** [comment]
我的JJQQKK右键启动chromium就没反应。。。

**Comment by xueming-xing** [comment]
我的无法访问谷歌,好多网站是不是作者屏蔽了,老是响应时间过长
