### ISSUE TITLE
win10的1903版，点启动VPN没有反应

### ISSUE THREAD

**Issue by MansonWu123** [jjqqkk/chromium#231]
点启动VPN没有反应，以为更新之后可以，可是从之前的2.4.0开始到现在这个版本都不行。chromium倒是可以正常用。

**Comment by jjjjax** [comment]
测试了一下，我也是这样的。 在公司是win7， 在家win10， 公司可用，家里不行。

**Comment by MansonWu123** [comment]
@jjjjax 我就是这种情况
