### ISSUE TITLE
现在可以用了

### ISSUE THREAD

**Issue by summersir** [jjqqkk/chromium#233]
现在能用了，mac和 Windows都可以用了，不过这里的版本还是2.5.1，自动更新已经到2.5.2了

**Comment by citrusyahello** [comment]
速度怎么样，我这校园网好慢...

**Comment by mimixingzhe** [comment]
我怎么点chromium还是没反应啊

**Comment by summersir** [comment]
> 我怎么点chromium还是没反应啊
他没有做版本号，我也就是更新的时候看到了一下，我的的确能用
