### ISSUE TITLE
安装最新版本谷歌插件置灰了，不支持插件安装了

### ISSUE THREAD

**Issue by ainidewowjf** [jjqqkk/chromium#234]
有解决办法吗？现在什么插件都无法安装，想搞个页面翻译都不行哎。。。。。。

**Comment by rongrong0501** [comment]
不会啊

**Comment by ainidewowjf** [comment]
扩展插件那个是置灰的；完了在扩展商城里下载插件无法安装；提示未开启安装






在 2019-10-16 17:37:07，"rongrong0501" <notifications@github.com> 写道：


不会啊

**Comment by ainidewowjf** [comment]
在 2019-10-16 17:37:07，"rongrong0501" <notifications@github.com> 写道：


不会啊

**Comment by dreamjn** [comment]
一直都不能装插件

**Comment by ainidewowjf** [comment]
怎么才能安装？有解决办法？





在 2019-10-18 09:10:00，"dreamjn" <notifications@github.com> 写道：


一直都不能装插件
