### ISSUE TITLE
2.5.1怎么更新到2.5.2？

### ISSUE THREAD

**Issue by lynn-liu-music** [jjqqkk/chromium#237]
我这边一直提示要更新，无法打开，但是也没有像之前一样跳出更新的窗口

**Comment by Chris-Liang0107** [comment]
我一直都是无法打开。。以前是全部卸掉重新装一回，这次不行了

**Comment by lynn-liu-music** [comment]
> 我一直都是无法打开。。以前是全部卸掉重新装一回，这次不行了

我也试了你这种方法 也是不行

**Comment by sheji-sm** [comment]
应该作者被抓了~到现在都不更新
