### ISSUE TITLE
连接 VPN 时不启动 Chromium

### ISSUE THREAD

**Issue by bbbear2002** [jjqqkk/chromium#239]
每次连接 VPN 时都会自动启动 Chromium，很不方便，能否取消这个设置？
我发现在 JJQQKK 中启动 Chromium，所有的插件都会消失。但单独启动 Chromium，插件又会回来。
所以没有必要在连接 VPN 时自动启动 Chromium。

**Comment by CHINAing** [comment]
现在Chromium能用吗？已经失联很久了

**Comment by bbbear2002** [comment]
每次连接 VPN 后都要关闭 Chromium，很不方便。
