### ISSUE TITLE
无法打开此安装包。请确认该程序包存在......

### ISSUE THREAD

**Issue by mroctopus1997** [jjqqkk/chromium#241]
求解
![image](https://user-images.githubusercontent.com/34855998/67676408-62e73c00-f9bc-11e9-80a9-d195630b3db7.png)

**Comment by Explorersss** [comment]
+1

**Comment by Explorersss** [comment]
卸载重装才能用,下次要用还要再次卸载重装

**Comment by rabbit-tank5352** [comment]
+1

**Comment by fufuYan** [comment]
咋整的啊

**Comment by music011** [comment]
杀毒删了10.msi，想卸载重装，卸载也要这个文件...怎么搞啊

**Comment by LiZhenghao1998** [comment]
> 卸载重装才能用,下次要用还要再次卸载重装

下载重装也不行啊2.6.1版本，新版进不去
