### ISSUE TITLE
升级到2.6.0之后

### ISSUE THREAD

**Issue by lawytang84** [jjqqkk/chromium#243]
一，升级到260之后，可用流量只有500M，若是不够怎么办？需要付费了么？
二，界面有个选项“免费加流量”，点击之后，等待40多秒，会有一个按键，点击后提示已经免费加了流量，但是界面显示还是只有500M，并未增加。这是为什么呢？

**Comment by lawytang84** [comment]
千万别更新，想降级回253都不可以

**Comment by jjqqkk** [comment]
先送500玩一玩 低于100才能加满100 收费在计划之内
