### ISSUE TITLE
mac最新版2.6.0无法免费加流量，返回201

### ISSUE THREAD

**Issue by 124591524** [jjqqkk/chromium#244]
点击免费加流量，流量没有增加，返回状态码201

**Comment by zzuboss** [comment]
+1

**Comment by jjqqkk** [comment]
有没有截屏 哪里201

**Comment by 124591524** [comment]
以下为截个图，点击免费获取流量后，提交到checkin后返回201，应该是后台处理错误吧
![1573604525652](https://user-images.githubusercontent.com/41882973/68721833-b37eac00-05ee-11ea-9684-b4788139fb43.jpg)

**Comment by privking** [comment]
+1

**Comment by jjqqkk** [comment]
HTTP status code 201, created, 意思就是已经加满100
