### ISSUE TITLE
200 兆流量 签到领20兆  顶多看半小时视频 

### ISSUE THREAD

**Issue by 252297606** [jjqqkk/chromium#248]
不如直接改成收费模式   签到只有第一次给流量 貌似20兆   220兆 基本看不完一个长点的视频 可以出各种套餐 让人选择  虽然免费了  那点流量 没太大意义

**Comment by gosevvv** [comment]
同意，如果只有200m可用，我觉得还不如收费，而且强制关闭浏览器太不方便，很多东西都没法留住突然就关了，还不如改成断掉，好歹给个保存的机会啊

**Comment by citrusyahello** [comment]
一天200m大概只能看看推特了...话说以前的版本不更新已经用不了了吗

**Comment by jjqqkk** [comment]
签到加满100不限次数
