### ISSUE TITLE
新版各种bug

### ISSUE THREAD

**Issue by lmhamy** [jjqqkk/chromium#257]
签到功能我可以接受，但是根本签不了，签了几次也不加流量。要不然就是十分难签，每次都提示错误。
直接代理也是总掉线，很不稳定，每次都要重开jjkk。
希望先解决这个直接代理不稳定问题。

**Comment by jjqqkk** [comment]
服务器用到极限了 会慢慢好起来

**Comment by XiaowuAiMC** [comment]
> 服务器用到极限了 会慢慢好起来

为什么我浏览比掉线速度快?
