### ISSUE TITLE
我的就是自动更新的但是点签到没有反应

### ISSUE THREAD

**Issue by 577938574** [jjqqkk/chromium#258]

**Comment by foundwant** [comment]
更新的太快了；
一提示更新老版就不能用了；
每次更新都不能自动下载替换，还要来github搜索下载安装包再安装；

**Comment by jjqqkk** [comment]
有没有错误提示？应该是自动下载

**Comment by EliBauer** [comment]
![Snipaste_2019-11-16_16-13-09](https://user-images.githubusercontent.com/47693193/68990247-02953d00-088c-11ea-84cd-5901c75d7db8.png)

**Comment by foundwant** [comment]
有提示错误的，一个错误弹框，下次遇到时我截图发这里


| |
王振
|
|
邮箱：foundwant@163.com
|

签名由 网易邮箱大师 定制

在2019年11月15日 14:37，JJQQKK 写道：

有没有错误提示？应该是自动下载
