### ISSUE TITLE
致JJQQKK：新版本的几个问题集中反映

### ISSUE THREAD

**Issue by truelord007** [jjqqkk/chromium#265]
第一、新版本有了流量限制；老版本则是畅用；
第二、流量限制只能手动方式来获取，自动的模式没有任何反应，是个摆设；
第三、手动方式的获取方式：必须首先用代理方式启动浏览器，然后才能点按那个手动获取流量按钮，然后才能上网，否则无反应；
第四、浏览器比以前慢了50%-100%，全程各种卡顿

希望JJQQKK：
改良自动获取流量方式；真正实现自动更新获取流量；
或者
像以前一样，不要设置流量门槛了，用起来很不顺

**Comment by PPDF** [comment]
表示在公司域内，完全没办法开，以前浏览器直接可以作为梯子，现在根本没办法上了。

**Comment by truelord007** [comment]
新版非常不稳定，不知道作者为什么会放这个版本出来？！不懂！
