### ISSUE TITLE
新版本更新后，有了流量限制，几分钟浏览器就自动关闭了

### ISSUE THREAD

**Issue by Jackie1023** [jjqqkk/chromium#266]
请问，是不是以后都会有不到200兆的流量限制了？自从11月15日更新后，就非常不好用了，网页打开十分卡顿，浏览3分钟或者5分钟后，浏览器会自动关闭，还能回到之前的老版本吗？

**Comment by lidanlei** [comment]
安卓,苹果,Mac,Windows 好用的加速器 刷INS、访推特，完美支持高清1080P视频，无任何流量限制,真正免费的加速器 https://n.antss044.xyz/aff/GFvA   试试这个吧  蚂蚁VPN  现在就是不好用了  又慢又容易断  只有先用用其他的救救急
