### ISSUE TITLE
自动签到，手动签到都没有用

### ISSUE THREAD

**Issue by privking** [jjqqkk/chromium#267]
自动签到，手动签到都没有用，200mb用完了就没了，完全没有体验度，不理解签到的理由是什么，现在免费的确实很难找，直接做成收费的也不是不能理解，价钱合理就能接受。希望再做一个适配ios的。

**Comment by wocaozhongguo** [comment]
说的对

**Comment by lidanlei** [comment]
安卓,苹果,Mac,Windows 好用的加速器 刷INS、访推特，完美支持高清1080P视频，无任何流量限制,真正免费的加速器 https://n.antss044.xyz/aff/GFvA  试试这个吧   蚂蚁VPN    先救急用   至于签到  手动签到是会跳一个网页出来  然后有一个签到按钮   如果当时无法连接的话  这个网页就没法用   要在可以连接的时候签到的...

**Comment by jjqqkk** [comment]
今天新版总算稳定了 系统被攻击 只能临时限流
