### ISSUE TITLE
更新了新版本后频繁断线

### ISSUE THREAD

**Issue by momi0099** [jjqqkk/chromium#268]
之前没什么问题，前几天更新完新版本后开始出现断线情况，从几小时有一次到现在短的5分钟长的也不到20分钟就要断一次，需要退出重新打开才能连接，有时需要重复几次才能连上……不知大家有没有这情况……

**Comment by MISSCHERYLWANG** [comment]
现在已经连不上了，而且流量还有限制。。。

**Comment by Jackie1023** [comment]
不会是不让免费试用了吧？？

**Comment by Jackie1023** [comment]
不会 不让免费使用了吧？？

**Comment by guangg1975** [comment]
完全是同样的情况。估计是要准备收费了。但是收不收费，赶紧定下来。现在这个状态使用起来太麻烦。

**Comment by citrusyahello** [comment]
最近速度实在太慢了...感觉更新得不太成功啊

**Comment by wocaozhongguo** [comment]
限流量了  没流量了 就关了

**Comment by lidanlei** [comment]
安卓,苹果,Mac,Windows 好用的加速器 刷INS、访推特，完美支持高清1080P视频，无任何流量限制,真正免费的加速器 https://n.antss044.xyz/aff/GFvA   试试这个  蚂蚁VPN   我目前就用这个顶着  看之后会不会有好转
