### ISSUE TITLE
开启VPN后网络自动断开

### ISSUE THREAD

**Issue by SwordOfOath** [jjqqkk/chromium#270]
新版本后开启VPN后网络自动断开，点击断开VPN后网络又自动重新连接。

**Comment by lidanlei** [comment]
安卓,苹果,Mac,Windows 好用的加速器 刷INS、访推特，完美支持高清1080P视频，无任何流量限制,真正免费的加速器 https://n.antss044.xyz/aff/GFvA  蚂蚁VPN  试试这个吧   先顶一顶
