### ISSUE TITLE
不会是 不让免费使用了吧？好难过

### ISSUE THREAD

**Issue by Jackie1023** [jjqqkk/chromium#271]
哎~~~~ 用不了好难过。。。。

**Comment by guangg1975** [comment]
刚才系统又更新了。不知道这次怎么样。

**Comment by guangg1975** [comment]
还是不行，2分钟就废了。

**Comment by wocaozhongguo** [comment]
我也是 不让用乐 限流量了

**Comment by lulu0426** [comment]
我这里才有15M的流量，用完等10分钟，这还怎么用？

**Comment by lidanlei** [comment]
安卓,苹果,Mac,Windows 好用的加速器 刷INS、访推特，完美支持高清1080P视频，无任何流量限制,真正免费的加速器 https://n.antss044.xyz/aff/GFvA   试试这个  最近用的  挺不错

**Comment by vieyellow** [comment]
最近限制流量了，大家先用蚂蚁加速器看看https://antss.orxs.me/aff/GRsH
