### ISSUE TITLE
为什么不让免费用了啊  限流了？？？？

### ISSUE THREAD

**Issue by wocaozhongguo** [jjqqkk/chromium#273]
为什么不让免费用了啊  限流了？？？？？

**Comment by lulu0426** [comment]
同问，如果以后这样的话还是换软件吧，这个基本废了。

**Comment by qiusister** [comment]
最近限制流量了，先用蚂蚁加速器顶一段时间看看
https://n.antss045.xyz/aff/GDF8

**Comment by wocaozhongguo** [comment]
真完蛋了 看来

**Comment by vieyellow** [comment]
最近限制流量了，大家先用蚂蚁加速器看看https://antss.orxs.me/aff/GRsH

**Comment by rcq2200** [comment]
卸载了

**Comment by rcq2200** [comment]
就是一个撒比玩意 大家都卸载吧
