### ISSUE TITLE
断线太快，平均5分钟就断线一次

### ISSUE THREAD

**Issue by Martin8829** [jjqqkk/chromium#274]
断线之后只能重新启动浏览器，签流量页强制在第一页，严重影响使用体验。望改进，谢谢！

**Comment by lulu0426** [comment]
限流量了，没了流量应该就断网吧，不好用了。

**Comment by Martin8829** [comment]
流量到100左右会自动签到领到200，不是因为没流量断网，是过几分钟就直接断网未连接到互联网了，很频繁！只能关闭浏览器重新打开才行，循环往复。。。。。。

**Comment by lulu0426** [comment]
我是直接不能用了，显示10分钟后自动分配流量，分配完就15M能干什么，开个网页就没了，不过有流量的时候也经常断网，不知道以后还能不能用了。

**Comment by Martin8829** [comment]
我也有过一次没签上流量，过10分钟分配了15M，用15M直接手动签到完全够用，签到200。我就是这么再继续签上使用的，但是现在几分钟就断网，已经没法正常使用了。。。。

**Comment by citrusyahello** [comment]
稳定性比之前差了好多，使用也更繁琐了

**Comment by qiusister** [comment]
新版增加流量限制了，用用蚂蚁加速器https://n.antss045.xyz/aff/GDF8，暂时顶一段时间看看

**Comment by qiusister** [comment]
最近限制流量了，先用蚂蚁加速器顶一段时间看看
https://n.antss045.xyz/aff/GDF8

**Comment by vieyellow** [comment]
最近限制流量了，大家先用蚂蚁加速器看看https://antss.orxs.me/aff/GRsH

**Comment by 252297606** [comment]
200兆 我用了半天都没用完  几秒就断线 基本用不了 哈哈
