### ISSUE TITLE
妈的有病

### ISSUE THREAD

**Issue by caengcjd** [jjqqkk/chromium#278]
开个一分钟然后马上关了不给用, 他们的你们至于吗？ 要么干脆别给人用了得了, 用了都用不成。什么傻逼玩意，有你们这玩的吗？

**Comment by zszs0012** [comment]
真的是看不下去，楼上这位请你在爆粗骂人之前先想一想这个梯子他是免费的，你可以选择用或者选择不用，没有人逼你，在这骂人你至于吗？

**Comment by amber06** [comment]
同意楼上 梯子是免费的 你不喜欢可以换收费的用

**Comment by zhulinxiaohai** [comment]
使用免费的东西，在骂人这就不对了，作者的初衷肯定不一分钟一掉线呀，处理问题总要时间的。

**Comment by 68891191** [comment]
免费白嫖这么久 还骂人，你真是垃圾人。。

**Comment by citrusyahello** [comment]
你这么牛逼你自己搭梯子啊，作者欠你钱了你爆粗？

**Comment by Chrisjiajun** [comment]
估计是小红粉好久没有去墙外宣泄他的爱国主义仇恨了憋的慌 就自己不会找个树洞么？真的是~

**Comment by njuse11wu** [comment]
> 估计是小红粉好久没有去墙外宣泄他的爱国主义仇恨了憋的慌 就自己不会找个树洞么？真的是~

你从哪儿看出这人是小粉红的？我倒觉得你像红卫兵，扣帽子一流~~

**Comment by Chrisjiajun** [comment]
> > 估计是小红粉好久没有去墙外宣泄他的爱国主义仇恨了憋的慌 就自己不会找个树洞么？真的是~
> 
> 你从哪儿看出这人是小粉红的？我倒觉得你像红卫兵，扣帽子一流~~

小红粉长什么样是要拿眼睛看的么?你自己照照镜子不就知道了~是呀红卫兵扣帽子一流我很赞成你说的这句话~也不知道你在骂谁~骂你自己么?照下镜子看你自己是小红粉还是红卫兵~反正我看也差不多~

**Comment by njuse11wu** [comment]
相信你一定听过一个讽刺故事：一个人每天都会给乞丐1块钱，但是有一天他没带钱，

> > > 估计是小红粉好久没有去墙外宣泄他的爱国主义仇恨了憋的慌 就自己不会找个树洞么？真的是~
> > 
> > 
> > 你从哪儿看出这人是小粉红的？我倒觉得你像红卫兵，扣帽子一流~~
> 
> 小红粉长什么样是要拿眼睛看的么?你自己照照镜子不就知道了~是呀红卫兵扣帽子一流我很赞成你说的这句话~也不知道你在骂谁~骂你自己么?照下镜子看你自己是小红粉还是红卫兵~反正我看也差不多~

疯狗一般的红卫兵，本质上与小粉红无异，只会扣帽子无脑喷，实则完全没有逻辑能力，畜生一条~

**Comment by njuse11wu** [comment]
很好的诠释了什么叫“升米恩斗米仇”。垃圾人应该被垃圾分类~

**Comment by Chrisjiajun** [comment]
哎 github都充斥五毛红粉 好累 还不停的骂自己 还自以为是 可怕可怕~

**Comment by njuse11wu** [comment]
> 哎 github都充斥五毛红粉 好累 还不停的骂自己 还自以为是 可怕可怕~

哈哈哈哈哈哈哈哈哈哈，戏精+啊q精神被你演绎的好到位啊，希望你千万别删之前的回复，让大家都看看笑话~
ps：这个帖子从头到尾和小粉红有半毛钱关系吗，上来就扣帽子逻辑真是负的，给自己加戏累不？看你演的这么累，给个link吧，我可以考虑赞助你一点~

**Comment by Chrisjiajun** [comment]
> > 哎 github都充斥五毛红粉 好累 还不停的骂自己 还自以为是 可怕可怕~
> 
> 哈哈哈哈哈哈哈哈哈哈，戏精+啊q精神被你演绎的好到位啊，希望你千万别删之前的回复，让大家都看看笑话~
> ps：这个帖子从头到尾和小粉红有半毛钱关系吗，上来就扣帽子逻辑真是负的，给自己加戏累不？看你演的这么累，给个link吧，我可以考虑赞助你一点~

翻墙出去张口闭口就骂人的是什么人大家不懂么？一说小红粉就跳起来的是什么人大家不懂么？
