### ISSUE TITLE
我知道开发不容易，免费不容易，可是这样被迫看广告真的很影响工作。

### ISSUE THREAD

**Issue by lmhamy** [jjqqkk/chromium#284]
我知道开发不容易，免费不容易，可是这样被迫看广告真的很影响工作。
其实我真心想要出付款模式的，不知道广告能带来多少钱，但是如果你不比市面高的价钱我是能接受的。
大家最不能接受的，那些收了钱网速不达标，而且还走路的VPN。
这几天的新版比往常网速要好（我个人而言看Pinterest够用了）。
我就是想用VPN来工作，但是你这样频繁弹出签到，真的有点影响我工作了。
自动签到的功能要不就关掉，有需要再开。
再说多一次，只要你收钱不走路，网速和收费的价钱能合理。我都不介意给钱的。

**Comment by citrusyahello** [comment]
你是工作需要的话，建议还是去找付费vpn吧，这个最近真的不太稳定

**Comment by Double-max** [comment]
谢谢你的提醒，不过我就是偶尔翻墙刷刷fb，ins，自己搭建了ss的，勉强能用





------------------ 原始邮件 ------------------
发件人: citrusyahello <notifications@github.com&gt;
发送时间: 2019年11月24日 00:39
收件人: jjqqkk/chromium <chromium@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[jjqqkk/chromium] 我知道开发不容易，免费不容易，可是这样被迫看广告真的很影响工作。 (#284)




你是工作需要的话，建议还是去找付费vpn吧，这个最近真的不太稳定

**Comment by lmhamy** [comment]
> 你是工作需要的话，建议还是去找付费vpn吧，这个最近真的不太稳定

我就是付过了，除了express vpn，付过的都很多走路了.....我买了express好几年，这几年价格真的高到不想付了。请拜托你告诉我哪个稳定付费不走路的vpn吧。我真的是怕了那些付费没多久就跑路的了。

**Comment by jjqqkk** [comment]
@lmhamy 有些问题不是付费能解决的 除非在天上有自己卫星 走海底光缆全都一条路 需要点时间调整 估计还需要几周 如果实在想付费可以开一个paypal打赏link 不过实话实说 这个跟质量没有任何关系 但我们不会跑路 因为不是商业化做这个 只是做浏览器做着做着拿一块技术出来玩玩而已 大家喜欢玩的就一起玩 至今没收一分钱 现在稍微有点变化你也可以猜到确实遇到点问题 技术上讲这里比跑路的先进很多 希望过几周能回到原来的样子

**Comment by Jackie1023** [comment]
- [ ] 

1. 

- 

> @lmhamy 有些问题不是付费能解决的 除非在天上有自己卫星 走海底光缆全都一条路 需要点时间调整 估计还需要几周 如果实在想付费可以开一个paypal打赏link 不过实话实说 这个跟质量没有任何关系 但我们不会跑路 因为不是商业化做这个 只是做浏览器做着做着拿一块技术出来玩玩而已 大家喜欢玩的就一起玩 至今没收一分钱 现在稍微有点变化你也可以猜到确实遇到点问题 技术上讲这里比跑路的先进很多 希望过几周能回到原来的样子

谢谢作者，真心感谢，我一直认为你做的这个浏览器非常好，而且很感激的是一直没有收费。没问题，可以等待的，期待可以回到从前没有限流量的日子。

**Comment by guangg1975** [comment]
终于等到作者的回信了。希望不要等几个周。越快越好。因为工作需要。用其他付费VPN，有个缺点。连上后，进国内网站，速度就降下来了。这样我就要连上后，过一会又要断掉。这个浏览器，没有这个问题。所以已经产生了严重的依赖。希望作者尽快让它稳定下来。

**Comment by jjqqkk** [comment]
@lmhamy  @guangg1975 @Jackie1023  @citrusyahello @Double-max  本周应该会出一个新版本 降低签到弹出几率 尽量减少对用户干扰 之前几周 确切说从九月底开始 系统遇到巨大的黑客流量 签到加流量之后至少过滤掉上百个TB的可疑流量 当然这种化疗式的做法得罪了正常用户 非常抱歉 我们很少有时间打理JJQQKK 修改软件时没有考虑周到 请各位见谅

由于这个系统完全匿名使用 不需要登录 未来如果遇到攻击 可能还是会采取应急措施 

另外之前提到过的 某国对外的光缆就一条路 没有任何收费服务能够保证质量 如果由我们来监管某国网络 能出来的估计更少 😄目前其实是G开头的公司在帮助大家 以后还请举手之劳 点一点广告

**Comment by lmhamy** [comment]
谢谢作者的认真回复，其实我也不抗拒点广告，有时候都会点一下。广告弹出的事情是激动了点，抱歉。因为之前版本实在是弹得太频繁。如果是为了滤掉黑客流量，能不能还有其他方式？
我也是每遇到一个用心开发的开发者都想支持一下，这些都不容易我们是知道的。希望以后能更好吧。加油！

JJQQKK <notifications@github.com> 于2019年11月26日周二 下午10:43写道：

**Comment by jjqqkk** [comment]
@lmhamy 要看对方只是蹭蹭流量还是很严肃认真地攻击 遇到高手我们也只能认怂 反正不登录不用账号是很难区分谁是谁的 以前还有人用我们的免费服务做了一个收费服务 真让人羡慕 做了我们一直想做但没做的事 还有就是这次签到页面第一天就被黑掉了 某些人读了页面代码后可以用他们自己的程序自动续签 伤害不大也就算了

**Comment by jjqqkk** [comment]
更新了

**Comment by CatMiaogu** [comment]
> @lmhamy 有些问题不是付费能解决的 除非在天上有自己卫星 走海底光缆全都一条路 需要点时间调整 估计还需要几周 如果实在想付费可以开一个paypal打赏link 不过实话实说 这个跟质量没有任何关系 但我们不会跑路 因为不是商业化做这个 只是做浏览器做着做着拿一块技术出来玩玩而已 大家喜欢玩的就一起玩 至今没收一分钱 现在稍微有点变化你也可以猜到确实遇到点问题 技术上讲这里比跑路的先进很多 希望过几周能回到原来的样子

作者辛苦了，之前的版本稳定，网速也快，是我用过最好的免费梯子了。希望能继续维护下去
