### ISSUE TITLE
Win10 安装2.6.6时出错

### ISSUE THREAD

**Issue by WilsonPong** [jjqqkk/chromium#290]
Win10 版本1903 （OS内部版本：18362.476）
安装时提示错误

![problem](https://user-images.githubusercontent.com/50487632/69960604-d395f100-1544-11ea-979a-27ffadae8a70.png)

之前一直在用2.6.3的，一直不提示升级，就自己下载2.6.6安装，但提示上图错误，然后把2.6.3卸载重新安装2.6.6，还是提示上面的错误，而我又没有备份2.6.3的安装文件，现在又安装不上新版，请教要怎么解决？

**Comment by jjqqkk** [comment]
重新下载一次 http://5.1.70.143/JJQQKK-2.6.6.msi 
大陆速度慢的话用迅雷下载 关闭所有管家 安装
