### ISSUE TITLE
请问有没有linux版本的

### ISSUE THREAD

**Issue by as7212325** [jjqqkk/chromium#3]
我是linux用户但是好像只有win和mac的请问能不能编译个deb的linux文件

**Comment by free-vpn** [comment]
@as7212325 您好，后续版本可以build 64位linux chrome，不过linux需求量真的非常小，而且都是高手在用linux，我们这点技术可能是班门弄斧了

**Comment by waterstream** [comment]
同求deb包

**Comment by minoyi** [comment]
同求deb包

**Comment by kekemuyu** [comment]
I think a lot of programers use linux system,so the linux chrome necessary

**Comment by quchunguang** [comment]
强烈需求deb包
