### ISSUE TITLE
打开白屏

### ISSUE THREAD

**Issue by foxydon** [jjqqkk/chromium#34]
win7旗舰64bit
版本6.1（内部版本7600）
打开什么都不显示，就一个框框里边白屏，最小化再恢复变成黑屏。开始以为chromium版本太高不兼容，下载原版chromium正常使用

**Comment by free-vpn** [comment]
ok thanks

**Comment by FinchWWW** [comment]
我也有相同的问题，我的是win8旗舰版64bit，打开后只剩下最大化/最小化和关闭的边框，里面是白屏的，最小化再恢复也变成黑屏，请问这是什么原因呀，其他的浏览器都能正常使用，谢谢啦！

**Comment by wuyow** [comment]
很棒的应用，WIN10可以很好的工作！WIN7打开是白板，看来只支持WIN10系统呀。升级到71版，仍然不支持WIN7。不知是否有方法解决？毕竟现在使用WIN7的用户还是不少的。谢谢！

**Comment by wuyow** [comment]
这个问题根据热心网友的回复方法解决了，下载[DirectXRepair](https://yesvrok.ctfile.com/fs/17431793-335731777)修复一下就好了
