### ISSUE TITLE
闪退报告

### ISSUE THREAD

**Issue by itnewgay** [jjqqkk/chromium#36]
感谢FREEVPN。 现在已经用上71版本了。   闪退情况还是经常发生。  比如我打开cloud.google.com 几乎每次都会闪退。 还有其它的一些网站，有可能是原来打开没事。但是不知道什么时候就会闪退了。只要是打开这个页面就闪退。  建议用官方稳定版浏览器吧。

再次感谢FREEVPN。 辛苦了！

**Comment by wei-xing** [comment]
> 感谢FREEVPN。 现在已经用上71版本了。 闪退情况还是经常发生。 比如我打开cloud.google.com 几乎每次都会闪退。 还有其它的一些网站，有可能是原来打开没事。但是不知道什么时候就会闪退了。只要是打开这个页面就闪退。 建议用官方稳定版浏览器吧。
> 
> 再次感谢FREEVPN。 辛苦了！

好像是因为账号同步的问题，前几个版本就有了

**Comment by GaranYeon** [comment]
71版比之前版本好很多，但打开多几个网页就还是闪退

**Comment by xcger** [comment]
怎么升级freeVPN里的chromium版本呢？

**Comment by KorbinKe** [comment]
在这里怎么下载

**Comment by lolakers** [comment]
闪退怎么解决
