### ISSUE TITLE
打开某些网站会出现 400 Bad Request  

### ISSUE THREAD

**Issue by Prayere** [jjqqkk/chromium#38]
如题，同一个网址不是每次都出现，但是经常出现，有解决办法 吗

**Comment by free-vpn** [comment]
可能还是干扰 想封没彻底封掉 国外网络也不稳定 youtube, github都宕过了 以前从没发生过

**Comment by Prayere** [comment]
我测试过用这个浏览器比正常的浏览器网速会慢一半，这是正常的吗，我怀疑是网速问题出现400 Bad Request，网速时好时坏

**Comment by free-vpn** [comment]
@Prayere 您是怎么比较的？我们build的浏览器走的路由和其他浏览器完全不同，所以用访问同一个站点来比较速度是没有意义的。如果400错误是访问中国大陆网站时看到的，有可能是那些网站屏蔽国外ip。

**Comment by kaien365** [comment]
我也遇到相同的情况，偶然遇到
