### ISSUE TITLE
why win7 can not run it?

### ISSUE THREAD

**Issue by wanglang1995** [jjqqkk/chromium#39]
please help me

**Comment by wub722** [comment]
I met same question.
右键Chrome图标快捷方式的属性，在“目标”这里加入参数 --disable-gpu --disable-software-rasterizer. 
可以启动chromium,但无法服务网页.

**Comment by wuyow** [comment]
> 另外,主要是directX没有安装好,从网上下载
> http://8dx.pc6.com/xzx6/DirectXRepair_v3.8.zip,
> 然后安装DirectX Repair.exe修复.就可以运行chromium了

太棒了，非常感谢！这个方法果然解决了WIN7运行此浏览器白屏的问题！

**Comment by landy5372** [comment]
使用DirectXRepair_v3.8.zip 修复后还是不行啊 怎么办 显示网页崩溃
