### ISSUE TITLE
没有足够的app id

### ISSUE THREAD

**Issue by treeyiki** [jjqqkk/chromium#45]
这个事情怎么解决啊，这个chrome我没有办法登录同步我的数据。。

**Comment by treeyiki** [comment]
是不是人多了就不行了啊，我发现速度慢了好多啊现在。
youtube都看不了

**Comment by jjqqkk** [comment]
用最新版 https://github.com/jjqqkk/chromium/releases/tag/72.0.3626.96

id不够可以试试无痕模式（incognito mode），如果还不行也就没办法了，访问google同步api每天只有100次免费调用，超过100次google就会收我们钱，而我们的浏览器免费给大家用，没有收入，所以到100次就无法调用任何收费api
