### ISSUE TITLE
在谷歌商店里无法安装adblock插件

### ISSUE THREAD

**Issue by qzd1989** [jjqqkk/chromium#47]
安装提示: 未启用安装功能
![image](https://user-images.githubusercontent.com/3345241/52775835-8ca14280-307b-11e9-9bc0-e498d838fde1.png)

**Comment by ANANA** [comment]
me too

**Comment by jjqqkk** [comment]
adblock会拦截代理后的请求造成无法正常使用浏览器 全部禁掉是懒人解决方案
