### ISSUE TITLE
Chromium 72.0.3626.96 无法安装任何插件

### ISSUE THREAD

**Issue by ANANA** [jjqqkk/chromium#48]
今晚下载了72版本的Chromium,但是打开后拓展程序选项为灰色不可操作，且在chrome商店下载的任何插件都无法安装，提示未启用安装功能。

![qq 20190214220942](https://user-images.githubusercontent.com/28486408/52792294-fb939100-30a5-11e9-810b-b192dab08c6d.png)

![qq 20190214221033](https://user-images.githubusercontent.com/28486408/52792334-15cd6f00-30a6-11e9-8d56-c943255cab5b.jpg)

![qq 20190214221222](https://user-images.githubusercontent.com/28486408/52792336-16660580-30a6-11e9-977d-329ae52b5dd1.jpg)

**Comment by xushiyi521** [comment]
我的也是这个问题

**Comment by olko2018** [comment]
私も

**Comment by Tiandians** [comment]
用以前的70.x版本打开时还有插件，但是经常出现闪退问题。72.x以后版本应该是被Free-VPN删除了插件功能以避免与代理的冲突。这是官方的操作，不是软件问题。以后应该会解决吧

**Comment by wuyow** [comment]
我还要安装YOUTUBE下载插件呢，还是先用71版吧。。。

**Comment by Tiandians** [comment]
@wuyow 很可惜，所有老版本都将于2月底停服😭。

**Comment by jjqqkk** [comment]
@all 

Sorry for the trouble! 

Extensions (especially those ad-blockers that monitor URLs) would make the whole SSL VPN stuck. It would take us hundreds of hours to solve this problem by changing Chromium extension subsystem source code, for each version (72, 73, 74, ...). Fighting with particular extensions is not Google style. Disabling extension is quite a standard way just like mobile Chrome on Android and iOS.
