### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by spl1861126** [jjqqkk/chromium#51]
最新版本下载不了啊，几K之后就不动了

**Comment by Tiandians** [comment]
考虑到Github在国内会遭到GFW的骚扰，影响大家的下载，我以后会把Chromium的Releases包搬运至百度网盘供大家下载。这里是[地址](https://pan.baidu.com/s/1VdrnVBEhuGDprdJA1ekzMQ)

**Comment by jjqqkk** [comment]
@spl1861126 
Please download Chromium 73 from backup site, may be faster for Chinese friends
