### ISSUE TITLE
无法完整下载

### ISSUE THREAD

**Issue by 21mt101** [jjqqkk/chromium#52]
下载到35M就终止了，禁止下载

**Comment by yellowall** [comment]
yes

**Comment by Tiandians** [comment]
考虑到Github在国内会遭到GFW的骚扰，影响大家的下载，我以后会把Chromium的Releases包搬运至百度网盘供大家下载。这里是[地址](https://pan.baidu.com/s/1VdrnVBEhuGDprdJA1ekzMQ)

**Comment by jackzhou1985** [comment]
是的，下载20-30M就禁止下载了。

**Comment by 21mt101** [comment]
谢谢

jackzhou1985 <notifications@github.com> 于2019年2月16日周六 下午2:28写道：

**Comment by jjqqkk** [comment]
@21mt101 @jackzhou1985 @Tiandians  
Please download Chromium 73 from backup site, may be faster for Chinese friends

**Comment by jackzhou1985** [comment]
> backup site

Thank you very much.~!!

**Comment by 21mt101** [comment]
你好
使用这个PC端chromium
360杀毒软件提示：
程序正在创建BITS任务,可能造成系统关键文件被篡改,感染病毒木马,建议立即阻止
这个是要阻止吗？还是360软件报错

jackzhou1985 <notifications@github.com> 于2019年2月17日周日 下午4:23写道：

**Comment by jjqqkk** [comment]
您好，

 

我们自己的电脑从来没安装过任何中国大陆厂家开发的软件，您只能自己判断了。


 

Regards,

https://github.com/jjqqkk

 
 

Sent: Wednesday, April 17, 2019 at 10:37 AM
