### ISSUE TITLE
Chromium 72.0.3626.96 无法登陆google帐号

### ISSUE THREAD

**Issue by momi0099** [jjqqkk/chromium#53]
新下的win版Chromium，登录后可以正常浏览土鳖但无法登陆帐号，在输入帐号密码后点下一部跳转到
抱歉，出了点问题。请重试。试着登陆谷歌也是相同情况，不知咋回事……

**Comment by aston198300** [comment]
我也遇到同样的问题，之前版本就存在同样的问题，这次新版这一问题依旧存在。
I have the same problem. The previous version has the same problem, but this new version still has the same problem

**Comment by aston198300** [comment]
Hope Chromium can us Chrome Log in account,

**Comment by FarmerChina** [comment]
是的、 我还以为是我的电脑出问题了

**Comment by jjqqkk** [comment]
Download Chromium 73, and try to use Incognito Window to login G.
https://github.com/jjqqkk/chromium/issues/55

**Comment by zhousatjn** [comment]
https://support.google.com/chrome/answer/95464?co=GENIE.Platform%3DDesktop&hl=en
