### ISSUE TITLE
73这个版本仍然无法登录google账号

### ISSUE THREAD

**Issue by Triones009** [jjqqkk/chromium#55]
73这个版本仍然无法登录google账号，输入密码后总是弹出“抱歉，出了点问题，请重试”
![default](https://user-images.githubusercontent.com/43713575/52911592-b4451480-32e0-11e9-8674-c2abb6a70642.png)

**Comment by FarmerChina** [comment]
是的、我也出现这个问题

**Comment by Todakki** [comment]
没法加载扩展程序怎么办？不能用AD BLOCK了
![image](https://user-images.githubusercontent.com/18179767/52914012-7525bc00-32fe-11e9-8585-98099a4b6b3e.png)

**Comment by Todakki** [comment]
https://blog.csdn.net/zhangjiuding/article/details/78238300

**Comment by FarmerChina** [comment]
Mac 机器怎么解决？

**Comment by jjqqkk** [comment]
Try to use Incognito Window to login Google. Windows: shift + ctrl + n, mac: shift + command + n

**Comment by FarmerChina** [comment]
> Try to use Incognito Window to login Google. Windows: shift + ctrl + n, mac: shift + command + n

在隐身模式下可以登录，但是在正常的模式下无法正常登录不知道这种情况该怎么解决？

**Comment by hhhk47** [comment]
为什么下了 73版本的还是首页还是提示版本太低 2月底即将停用？？？？？？

**Comment by zhedielj** [comment]
> 73这个版本仍然无法登录google账号，输入密码后总是弹出“抱歉，出了点问题，请重试”
> ![default](https://user-images.githubusercontent.com/43713575/52911592-b4451480-32e0-11e9-8674-c2abb6a70642.png)

有个迂回的办法。先在隐身模式下登录，这样就会认为你的登录时安全的，然后再用正常模式登录，就不用验证了。

**Comment by sle1008** [comment]
> 73这个版本仍然无法登录google账号，输入密码后总是弹出“抱歉，出了点问题，请重试”
> ![default](https://user-images.githubusercontent.com/43713575/52911592-b4451480-32e0-11e9-8674-c2abb6a70642.png)

你验证的时候，填最后一项获取帮助，然后经过两步验证就可以了。这个原因很简单，谷歌检测到你的账号在异地登陆了，所以就限制你登录账号了。我们用vpn肯定会出现这个问题的

**Comment by TT1890155** [comment]
> > 73这个版本仍然无法登录google账号，输入密码后总是弹出“抱歉，出了点问题，请重试”
> > ![default](https://user-images.githubusercontent.com/43713575/52911592-b4451480-32e0-11e9-8674-c2abb6a70642.png)
> 
> 你验证的时候，填最后一项获取帮助，然后经过两步验证就可以了。这个原因很简单，谷歌检测到你的账号在异地登陆了，所以就限制你登录账号了。我们用vpn肯定会出现这个问题的

经过手机两步验证，还是会说抱歉。。。怎么办呀
