### ISSUE TITLE
为什么下了73版的依旧提示版本过低，旧版本即将停服？？

### ISSUE THREAD

**Issue by hhhk47** [jjqqkk/chromium#56]
为什么下了73版的打开主页后依旧提示版本过低，旧版本即将停服？？
![_](https://user-images.githubusercontent.com/47718332/52915591-fc7c2b00-3310-11e9-8243-d9d3457aa0a3.jpg)

**Comment by winter12138** [comment]
这可能是对所有网页访问者的提示。。。

**Comment by Arden2019** [comment]
查看版本对了就行了，那个网页提示是持续的。
