### ISSUE TITLE
73版本无法登录Google账号已解决，但又出现无法安装Chrome应用商店扩展程序问题

### ISSUE THREAD

**Issue by Triones009** [jjqqkk/chromium#57]
73版本无法登录Google账号已解决，但又出现无法安装Chrome应用商店扩展程序问题，安装扩展程序后，总是弹出“出现错误，未启用安装功能”窗口，查看Chromium 菜单项的“更多工具”--“扩展程序”，发现扩展程序选项一直灰色，无法点击。
![1](https://user-images.githubusercontent.com/43713575/52922748-77b7fe00-335e-11e9-8caf-dcce9a9aeafe.png)
![2](https://user-images.githubusercontent.com/43713575/52922752-7d154880-335e-11e9-9878-ed982f441d22.png)

**Comment by zhousatjn** [comment]
MacOS 下 73版 依然存在下述2个问题： 1）Google账户无法登录； 2）Chrome应用商店的扩展程序无法安装，提示“未启用安装功能”。 请尽管解决，谢谢！

**Comment by Tiandians** [comment]
请参照此Issue #48

**Comment by zhousatjn** [comment]
你好，谢谢！ 不过，MacOS 上还是无法登录Google账号，每次登录都报错；老版本登录则正常。

Zhu Baolin <notifications@github.com> 于2019年2月22日周五 下午11:08写道：

**Comment by zhedielj** [comment]
> 73版本无法登录Google账号已解决，但又出现无法安装Chrome应用商店扩展程序问题，安装扩展程序后，总是弹出“出现错误，未启用安装功能”窗口，查看Chromium 菜单项的“更多工具”--“扩展程序”，发现扩展程序选项一直灰色，无法点击。
> ![1](https://user-images.githubusercontent.com/43713575/52922748-77b7fe00-335e-11e9-8caf-dcce9a9aeafe.png)
> ![2](https://user-images.githubusercontent.com/43713575/52922752-7d154880-335e-11e9-9878-ed982f441d22.png)

你是怎么解决google account登录的？我想禁用这个free vpn，然后用我自己的vpn登录，但是不知道在哪里禁用

**Comment by zhousatjn** [comment]
你好！

打开Chromium 73版后，按 Shift + Command + N
开一个匿名窗口，在这个里面输入Gmail.com就可以了。你试试看，我是在MacOS上用的。
Windows基本思路一样，就是开一个匿名的窗口或者用匿名登录，按 Shift + Control + N。

tom <notifications@github.com> 于2019年2月23日周六 下午5:36写道：

**Comment by zhousatjn** [comment]
你好！ 打开Chromium 73版后，按 Shift + Command + N 开一个匿名窗口，在这个里面输入Gmail.com就可以了。你试试看，我是在MacOS上用的。 Windows基本思路一样，就是开一个匿名的窗口或者用匿名登录，按 Shift + Control + N。

**Comment by zhedielj** [comment]
> 你好！ 你的方法有用，多谢。今天更新了版本号，解决了这个登录问题。
