### ISSUE TITLE
Notify me the version is to be upgraded when download version 73.0.3683.27

### ISSUE THREAD

**Issue by vanti235** [jjqqkk/chromium#61]
Again, the app notify me that the version is still too old when I download the version 73.0.3683.27. Why?
I get the same results in MacOS 10.14 and Windows 10.

**Comment by jjqqkk** [comment]
oh that's a silly notice to inform all users who like our browser to get the latest build as soon as possible coz v72 and older versions will be totally broken by the end of Feb, the web page is not dynamic, it doesn't know you are using v73... so we say it is a silly notice. We will remove it in the next week.
