### ISSUE TITLE
扩展程序问题

### ISSUE THREAD

**Issue by winter12138** [jjqqkk/chromium#62]
今天才发现这个软件，然后发现不能安装扩展。我看了其他的issue，包括issue49，禁用扩展程序的原因是因为兼容adblock扩展需要额外的工作。那么可以不兼容adblock扩展，但是可以使用其他的扩展，比如油猴吗？扩展是chromium的灵魂啊。感谢开发者。

**Comment by Tiandians** [comment]
开发者已经答复，任何拓展都将与SSL起冲突，开发者没有时间去解决这个问题。鱼和熊掌不可兼得。

**Comment by winter12138** [comment]
理解
