### ISSUE TITLE
喔唷，崩溃啦

### ISSUE THREAD

**Issue by Drzha0** [jjqqkk/chromium#66]
![image](https://user-images.githubusercontent.com/47517032/53077014-0cbc2200-352c-11e9-86ad-1ef4be1e8871.png)
兼容模式下能运行，但是win10 打开就崩溃，设置界面都打不开

**Comment by a307633988** [comment]
你的解决了吗？

**Comment by chao921125** [comment]
不要用兼容模式，更新到最新版本73，然后打开就行。win10

**Comment by Kirito-bob** [comment]
打开后显示崩溃了怎么办？
