### ISSUE TITLE
扩展程序不能安装

### ISSUE THREAD

**Issue by ElwynZhang** [jjqqkk/chromium#68]
在更多工具选项中扩展程序颜色为浅黑色，无法使用此功能。
在设置中的扩展程序里chrome网上应用商店搜索的插件添加插件时都提示“出现错误，未启用安装功能”
<img width="278" alt="snipaste_2019-02-21_17-15-04" src="https://user-images.githubusercontent.com/46177799/53157340-4197aa00-35fc-11e9-8c9e-6258665dbd42.png">

**Comment by Tiandians** [comment]
请参照此Issue #48

**Comment by camyiori** [comment]
#48 没有解决这个问题。
从72 73开始都是x86的版本，这些都无法安装插件。并且73之前都不能用了对吧。那不能解决一下 插件 的问题么？ （官方版本是可以安装的）

还有，希望出个x64的74版。

**Comment by kaien365** [comment]
请问这无法安装插件，何时能解决呢？
