### ISSUE TITLE
腾讯电脑管家可以阻止翻墙

### ISSUE THREAD

**Issue by polarbearcn** [jjqqkk/chromium#72]
我用的WIN7系统，两个管理员级账户。在一个账户下运行过几次最新版的Chromium,但是后来就打不开页面了。注销后用另一账户（很少用）登录，运行Chromium又是正常的。于是再次登录先前的账户，关闭腾讯电脑管家，Chromium又可以成功翻墙。由此分析会不会是腾讯电脑管家收集到了翻墙的流量还是什么其他信息，导致翻墙失败。

**Comment by jjqqkk** [comment]
大陆任何一家大公司任何一款软件都可以监控网络 这并不让人意外 当然chrome稍加改造也能监控网络 也能反监控 不过国外公司没有时间精力资源参与这种低层次博弈
