### ISSUE TITLE
缺少Google API 密钥，73.0.3683.46

### ISSUE THREAD

**Issue by xnetproxy123** [jjqqkk/chromium#74]
![image](https://user-images.githubusercontent.com/48116668/53620860-6e1c7900-3c2f-11e9-801f-6dad956d2568.png)

**Comment by xnetproxy123** [comment]
How to correct this!

**Comment by Tiandians** [comment]
解决办法请参阅Issue #4 。官方在Relese 73.0.3683.46的详情中有说明原因：

> Chromium 73.0.3683.46

> This version fixes the Google login problem. But, when the browser is started, there will be such a notice showing up: "missing API keys... ".

> We have to remove some of API keys to allow UNLIMITED Google login. Otherwise, only 100 login attempts are allowed every single day, which is definitely not enough for our users.
