### ISSUE TITLE
为什么我下载不了

### ISSUE THREAD

**Issue by oukeikou** [jjqqkk/chromium#75]
下载不了

**Comment by oukeikou** [comment]
有没有百度网盘，或者其他的下载链接啊，备用地址也不行

**Comment by z511367698** [comment]
能不能不要群发啊？？？




                                                                        ————周洋
在2019年03月01日 16:34，oukeikou 写道：

有没有百度网盘，或者其他的下载链接啊，备用地址也不行

**Comment by lmznb** [comment]
可以下

z511367698 <notifications@github.com>于2019年3月1日 周五16:35写道：

**Comment by Tiandians** [comment]
请参阅Issue #52 。我有将安装包搬运至百度网盘，这里是[地址](https://pan.baidu.com/s/1VdrnVBEhuGDprdJA1ekzMQ) （https://pan.baidu.com/s/1VdrnVBEhuGDprdJA1ekzMQ）
