### ISSUE TITLE
崩溃的解决了

### ISSUE THREAD

**Issue by leoxxnet** [jjqqkk/chromium#78]
![image](https://user-images.githubusercontent.com/32661213/53681909-faf82d00-3d2a-11e9-9939-6fbc610d8287.png)
亲测完美解决！！！
大家可以试一下。

**Comment by jjqqkk** [comment]
😄

**Comment by lmhamy** [comment]
有用，google账号也登录上了。现在唯一问题上pinterest没法上

**Comment by qouson** [comment]
还是崩溃了

**Comment by jjqqkk** [comment]
Windows?
 

Sent: Thursday, March 14, 2019 at 9:04 AM

**Comment by BaronND** [comment]
两种方式都修改了，还是提示网站奔溃了，怎么说，就是把启动的文件名称改成chrom or chromuim不是么，还有其他的方式解决这个问题么？

**Comment by BaronND** [comment]
Both methods have been modified, but still the website crashed. In other words, the startup file name should be changed to chrom or chromuim, right? Is there any other way to solve this problem?

**Comment by jjqqkk** [comment]
Hi,

 

We are developing a Chromium launcher program for both Windows and macOS, which could download and launch the browser correctly. It is very likely to be published within a week (before May-10), and we hope the launcher solve your problem nicely.

 

You may also double check the following items on your side:

 

1. Make sure you are using the latest Chromium, 75.*

 

2. On Windows, make sure you have extracted all the files from the .zip. DO NOT run chromium.exe directly inside the zipped folder.

 

3. Pause (or stop) any monitoring app such as those made by 360 and Tencent. 

 

 

GOOD LUCK!

 

Regards,

https://github.com/jjqqkk

 
 

Sent: Monday, April 29, 2019 at 4:07 PM
