### ISSUE TITLE
cant get google services

### ISSUE THREAD

**Issue by zuherabud** [jjqqkk/chromium#79]
cant add extensions and cant sign in to google with this version of chromium

**Comment by jjqqkk** [comment]
"sign in" works. extension is disabled to protect vpn proxy settings.

**Comment by zuherabud** [comment]
sign in to google services works but signing in to chromium browser doesn't work

**Comment by zuherabud** [comment]
the previous version used to install extensions can i force an extension installation or you guys are dealing with the issue? i just need ad block plus extension no need of all others
