### ISSUE TITLE
打开不了了

### ISSUE THREAD

**Issue by KingPengZero** [jjqqkk/chromium#80]
开两会，是不屏蔽了，北京地区用不了【狗头】【狗头】

**Comment by jjqqkk** [comment]
73.0.3683.46?

**Comment by KingPengZero** [comment]
> 73.0.3683.46?

又可以访问了

**Comment by EalgeTang** [comment]
73.08683.46版本浏览器无法登陆 Google账号了,  这样就没办法做账号同步了

**Comment by chinaguopeng** [comment]
我也上不去了，Chromium-73.0.3683.67，我还有27的
