### ISSUE TITLE
73.08683.46版本浏览器无法登陆 Google账号

### ISSUE THREAD

**Issue by EalgeTang** [jjqqkk/chromium#81]
73.08683.46版本浏览器无法登陆 Google账号了, 这样就没办法做账号同步了

**Comment by EalgeTang** [comment]
对了, 我的是Mac 版本 版本 10.14.1

**Comment by Baifangchi** [comment]
我也登陆不了，10.1.4.3
![image](https://user-images.githubusercontent.com/26532557/54097909-3a8add00-43ed-11e9-8e0e-e60cd5b3c4d3.png)

**Comment by JaveyHE** [comment]
可以登录。不过你要设置下。
在设置<高级设置<把允许登录 Chromium开关关了就行

**Comment by JaveyHE** [comment]
我的是Windows，73.0.3683.27

**Comment by applejuicey** [comment]
set your Google API key to solve this problem

> https://blog.csdn.net/sinat_21302587/article/details/84960580

> https://blog.csdn.net/yori_chen/article/details/79654294
