### ISSUE TITLE
在这个浏览器下youtube搜索的时候会出现503

### ISSUE THREAD

**Issue by qzd1989** [jjqqkk/chromium#89]
打开chromium,打开youtube,随意搜索,百分百会进入https://www.google.com/sorry/index?continue=https://www.youtube.com/results%3Fsearch_query%3Dhello%26pbjreload%3D10&q=EgRo-puCGOLP7uQFIhkA8aeDS7v6gTpyw4vj6XFjDWMk4u8xvILRMgFy
这个界面,并且界面报503错误后不停reload,一直503,无法刷新出验证码.

![image](https://user-images.githubusercontent.com/3345241/55095186-aad67580-50f2-11e9-9bad-ef34fef3d5ac.png)

**Comment by jjqqkk** [comment]
是因为相同ip地址同时发出很多类似请求，Youtube需要确认不是机器人，至于验证码刷不出，是最近发生的问题，我们要和Youtube沟通一下。这个问题看起来是Youtube的问题，不是Google的问题，可以直接从Google搜索视频：

site:youtube.com keywords
