### ISSUE TITLE
越来越慢了,现在已经无法正常看youtube了

### ISSUE THREAD

**Issue by qzd1989** [jjqqkk/chromium#98]
之前还能看720P,1080P,现在144P都卡. 已排除我宽带的问题.

是不是用户变多了?

**Comment by gvc0461082002** [comment]
感觉不同的时间段，网速确实不一样。应该还好。要是慢的话，可以把Youtube link转化，然后下载，现在遇到网速慢的情况，我就是这样处理的。

**Comment by helloGC1** [comment]
我这也变慢了，同样的网速
